### ISSUE TITLE
Abnormal cursor position and component click events caused by gesture recognition

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1140] opened 2023-05-16 08:43 UTC
# Bug Description

super_editor: ^0.2.5

 When I click on the CheckBox, the editor should not gain focus. The click event should only be handled by the CheckBox. I looked at the source code and found that it was the "TapSequenceGestureRecognizer" that intercepted all click events. So I investigated this and compared it to the implementation of "TextField". I found that the problem could be solved by simply following the implementation of "TextField".

https://github.com/superlistapp/super_editor/assets/37604230/ae64e18d-f692-40dd-89dc-6b5b3f4d3fee

**Comment by raulmabe-labhouse** [comment] 2023-05-17 10:07
@Dboy233 Testing your solution on iOS, stable branch, Flutter 3.10.0, editor selection is broken (can't focus).

**Comment by Dboy233** [comment] 2023-05-17 14:21
@raulmabe-labhouse 

Since I didn't have an iPhone, I robbed a friend's phone to test it.

After I tested it, I found that using `TextSelectionGestureDetector` does not work properly on ios devices, so I found a replacement - `TapAndPanGestureRecognizer`. 

'TapDragDownDetails' has a member variable that counts the number of presses --- `consecutiveTapCount`.

`TextField` also uses this variable to judge multiple clicks.

iOS 'Scrollbar' doesn't seem to work properly. The reason may be that vertical scrolling events are being intercepted。

<img width="732" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/80d95aea-a8f6-4af9-bce8-4e5d7ee20c80">

<img width="757" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/6ae3555c-bb06-4930-a2ac-2bdea502bef9">

This is my test video：

iOS:

https://github.com/superlistapp/super_editor/assets/37604230/62f458e3-4a34-4e6f-a862-e6b11940427d

Android:

https://github.com/superlistapp/super_editor/assets/37604230/aeb6e077-d78b-4669-89b2-cb9eca5a5666


This zip file contains two files that I modified.

[change_code.zip](https://github.com/superlistapp/super_editor/files/11499096/change_code.zip)

**Comment by Dboy233** [comment] 2023-06-07 05:46
I think this issue should be taken seriously, as gesture operation is particularly important for mobile platforms.

**Comment by matthew-carroll** [comment] 2023-06-09 16:25
It's not clear to me what specific problem or problems are being described here.

I see a lot of reference to implementation code, but that's not particularly useful. I also see some mention of response time, but nothing specific.

If you'd like for us to address this, we need a very specific problem statement, including reproduction steps that demonstrate the issue.

**Comment by Dboy233** [comment] 2023-06-10 03:44
@matthew-carroll I updated the description

**Comment by matthew-carroll** [comment] 2023-06-13 20:41
@angelosilvestre it looks like the gesture interaction with the checkbox is also being applied to the editor, causing the caret to be placed and the keyboard to come up.

Now that I think about it, this issue might be the result of the fact that we still haven't migrated the mobile gesture structure to match desktop. If that's the case, then this issue is essentially a duplicate. But if that's not the issue, can you see why this might be happening?

**Comment by Dboy233** [comment] 2023-06-14 02:24
> @angelosilvestre it looks like the gesture interaction with the checkbox is also being applied to the editor, causing the caret to be placed and the keyboard to come up.
> 
> Now that I think about it, this issue might be the result of the fact that we still haven't migrated the mobile gesture structure to match desktop. If that's the case, then this issue is essentially a duplicate. But if that's not the issue, can you see why this might be happening?

@matthew-carroll This issue is caused by the gesture competition logic of "TapSequenceGestureRecognizer".  And I suggest using "TapAndPanGestureRecognizer" to detect multiple taps.  I have added a "change_code.zip" file in my previous reply which contains the optimized code I have written.

**Comment by Dboy233** [comment] 2023-06-16 05:50
@angelosilvestre  I'm not sure if you have started fixing this issue.

 I have already fixed this issue and created a branch called ["fix#1140"](https://github.com/Dboy233/super_editor/tree/fix%231140) in my repository.

 I have tested it by clicking on IOS, MAC, Android and the Web, and everything is working fine.

**Comment by angelosilvestre** [comment] 2023-06-21 23:58
@matthew-carroll It seems to be related to the widget tree structure.

This is the log for the gesture arena on desktop: 

```
flutter: Gesture arena 20   ❙ ★ Opening new gesture arena.
flutter: Gesture arena 20   ❙ Adding: TapGestureRecognizer#f9608(debugOwner: GestureDetector, state: ready, button: 1)
flutter: Gesture arena 20   ❙ Closing with 1 member.
flutter: Gesture arena 20   ❙ Default winner: TapGestureRecognizer#f9608(debugOwner: GestureDetector, state: possible, button: 1)
flutter:                    ❙ TapGestureRecognizer#f9608(debugOwner: GestureDetector, state: possible, button: 1) calling onTapDown callback.
flutter:                    ❙ TapGestureRecognizer#f9608(debugOwner: GestureDetector, state: possible, won arena, finalPosition: Offset(365.0, 42.0), finalLocalPosition: Offset(13.0, 18.0), button: 1, sent tap down) calling onTapUp callback.
flutter:                    ❙ TapGestureRecognizer#f9608(debugOwner: GestureDetector, state: possible, won arena, finalPosition: Offset(365.0, 42.0), finalLocalPosition: Offset(13.0, 18.0), button: 1, sent tap down) calling onTap callback.
```

On desktop, our `TapSequenceGestureRecognizer` didn't even enter in the arena.

This is the log for the gesture arena on mobile:

```
flutter: Gesture arena 21   ❙ ★ Opening new gesture arena.
flutter: Gesture arena 21   ❙ Adding: TapGestureRecognizer#c6b9a(debugOwner: GestureDetector, state: ready, button: 1)
flutter:                    ❙ TapSequenceGestureRecognizer#ea284 calling onTapDown callback.
flutter: Gesture arena 21   ❙ Adding: TapSequenceGestureRecognizer#ea284
flutter: Gesture arena 21   ❙ Adding: VerticalDragGestureRecognizer#84b47(start behavior: down)
flutter:                    ❙ VerticalDragGestureRecognizer#84b47(start behavior: down) calling onDown callback.
flutter: Gesture arena 21   ❙ Closing with 3 members.
flutter:                    ❙ TapGestureRecognizer#c6b9a(debugOwner: GestureDetector, state: possible, button: 1) calling onTapDown callback.
flutter:                    ❙ TapSequenceGestureRecognizer#ea284 calling onTapUp callback.
flutter: Gesture arena 21   ❙ Holding with 3 members.
flutter: Gesture arena 21   ❙ Rejecting: VerticalDragGestureRecognizer#84b47(start behavior: down)
flutter:                    ❙ VerticalDragGestureRecognizer#84b47(start behavior: down) calling onCancel callback.
flutter: Gesture arena 21   ❙ Delaying sweep with 2 members.
flutter:                    ❙ TapSequenceGestureRecognizer#ea284 calling onTimeout callback.
flutter: Gesture arena 21   ❙ Rejecting: TapSequenceGestureRecognizer#ea284
flutter: Gesture arena 21   ❙ Releasing with 1 member.
flutter: Gesture arena 21   ❙ Sweeping with 1 member.
flutter: Gesture arena 21   ❙ Winner: TapGestureRecognizer#c6b9a(debugOwner: GestureDetector, state: ready, finalPosition: Offset(370.0, 37.0), finalLocalPosition: Offset(18.0, 13.0), button: 1, sent tap down)
flutter:                    ❙ TapGestureRecognizer#c6b9a(debugOwner: GestureDetector, state: ready, won arena, finalPosition: Offset(370.0, 37.0), finalLocalPosition: Offset(18.0, 13.0), button: 1, sent tap down) calling onTapUp callback.
flutter:                    ❙ TapGestureRecognizer#c6b9a(debugOwner: GestureDetector, state: ready, won arena, finalPosition: Offset(370.0, 37.0), finalLocalPosition: Offset(18.0, 13.0), button: 1, sent tap down) calling onTap callback.
```

Because of the widget tree structure, our `TapSequenceGestureRecognizer` did enter the arena. However, even though the `TapSequenceGestureRecognizer` didn't win in the arena, it's still invoking the callbacks. We can see that `onTapDown` was called immediately. The recognizer should only invoke the callbacks if it wins in the arena.

**Comment by matthew-carroll** [comment] 2023-06-22 22:53
@angelosilvestre I'm not sure what to make of those details in isolation.

You said that desktop is different from mobile. Is desktop working and mobile isn't? Or vis-a-versa?

You said that the issue is based on our widget tree structure. Which widgets, and what structure is causing the issue?

**Comment by angelosilvestre** [comment] 2023-06-23 00:13
@matthew-carroll Desktop is working and mobile isn't.

I think the reason might be that, on desktop, the gesture interactor and the document layout are inside a stack.

Desktop:
![tree_desktop](https://github.com/superlistapp/super_editor/assets/7597082/c56b788c-b47e-41db-beea-7a87f1a67bad)

Mobile:
![tree_android](https://github.com/superlistapp/super_editor/assets/7597082/cc6e6a52-4457-42cc-b20f-4cda9a29a482)

**Comment by matthew-carroll** [comment] 2023-06-26 20:43
@angelosilvestre please try to connect the details to an explanation. Why do you think the `Stack` matters?

**Comment by angelosilvestre** [comment] 2023-06-27 00:20
@matthew-carroll I think that the fact that in the `Stack` the interactor is in the same depth as the document layout influences the hit-testing, but I'm not sure how to debug it.

**Comment by matthew-carroll** [comment] 2023-06-27 20:19
If we restructured the mobile layers to match the desktop layers, do you think that would solve the problem? We've had a ticket around for a long time to do that. I'm wondering if this is essentially a duplicate.

**Comment by Dboy233** [comment] 2023-06-27 21:54
> If we restructured the mobile layers to match the desktop layers, do you think that would solve the problem? We've had a ticket around for a long time to do that. I'm wondering if this is essentially a duplicate.

Yes, the question is repeated.

**Comment by Dboy233** [comment] 2023-06-27 22:02
Sorry, I clicked the wrong button because my hand was shaking.

**Comment by angelosilvestre** [comment] 2023-06-27 23:16
I think it's possible that changing to use the same structure as the desktop will solve the problem. We could try to move the Android interactor in a stack with the document layout to see if it will work before investing time in changing the layer structure.

**Comment by matthew-carroll** [comment] 2023-06-28 19:57
Ok. Let's give that a quick try to confirm.

**Comment by angelosilvestre** [comment] 2023-07-03 23:30
@matthew-carroll Using a stack the tapping at the checkbox and scrolling worked as expected. However, when tapping to change the selection a exception is thrown when we call `return _docLayout.getDocumentOffsetFromAncestorOffset(offset, context.findRenderObject()!);`:

```
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3167 pos 14: 'renderer.parent != null': is not true.
```

It might be the case that we need to move other widgets around, but I didn't dig deeper into this.

**Comment by matthew-carroll** [comment] 2023-08-09 19:08
@Dboy233 we've merged support for document layers on mobile. The document gestures now sit behind the component gestures. Can you please check whether this issue remains?

PR: https://github.com/superlistapp/super_editor/pull/1256

**Comment by Dboy233** [comment] 2023-08-10 00:37
@matthew-carroll Great, the issue with gestures has been resolved.

**Comment by matthew-carroll** [comment] 2023-08-10 00:38
In that case I'll close this issue.

**Closed by matthew-carroll** 2023-08-10 00:38 UTC
Labels: area_supereditor, bounty_junior, f:superlist, awaiting-customer-feedback, time:2
