### ISSUE TITLE
[SuperTextField] is breaking on Flutter beta

### ISSUE THREAD

**Issue by domesticmouse** [superlistapp/super_editor#792] opened 2022-09-26 02:49 UTC
SuperTextField 0.2.2 is failing on Flutter 3.4.0-17.2.pre

```console
$ flutter run -d macos
Running "flutter pub get" in super_text_editor_testing...        2,257ms
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001250C00C38801E }
{ platform:macOS, arch:x86_64, id:00006000-001250C00C38801E }
../../../.pub-cache/hosted/pub.dartlang.org/super_editor-0.2.2/lib/src/default_editor/document_input_ime.dart:73:7: Error: The non-abstract class '_DocumentImeInteractorState' is missing implementations for these members:
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _DocumentImeInteractorState extends State<DocumentImeInteractor> implements DeltaTextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:1172:8: Context: 'TextInputClient.performSelector' is defined here.
  void performSelector(String selectorName) {}
       ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/super_editor-0.2.2/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart:29:7: Error: The non-abstract class 'ImeAttributedTextEditingController' is missing implementations for these members:
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ImeAttributedTextEditingController extends AttributedTextEditingController implements DeltaTextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:1172:8: Context: 'TextInputClient.performSelector' is defined here.
  void performSelector(String selectorName) {}
       ^^^^^^^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```

Flutter doctor output:

```console
$ flutter doctor -v 
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.4.0-17.2.pre on channel beta at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision d6260f127f (4 days ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by matthew-carroll** [comment] 2022-10-01 21:39
I think this issue now relates to the current stable version. I'm going to close this ticket in favor of #801

**Comment by domesticmouse** [comment] 2022-10-02 23:56
> I think this issue now relates to the current stable version. I'm going to close this ticket in favor of #801 

There is a change inbound that isn't in Flutter 3.3.x but is in 3.4.x-beta.

You can see a PR for flutter samples that I believe is relevant to this issue: https://github.com/flutter/samples/pull/1447

**Comment by matthew-carroll** [comment] 2022-10-11 20:51
I'm re-opening this ticket because the problem is 3.4 and not 3.3.3, and 3.4 isn't stable yet.

**Closed** 2022-10-18 01:18 UTC
