### ISSUE TITLE
Caret moves into second last position when clicking in empty space after certain texts

### ISSUE THREAD

**Issue by Mijawel** [superlistapp/super_editor#799] opened 2022-09-29 05:28 UTC
Issue: Caret moves into second last position when clicking within empty space after certain texts.

How to replicate:
- Open up a super_editor text box on the latest current commit as of this post (fc25dcd) (I'm not sure what commit the example editor at https://editor.superlist.com/ is on but the issue appears there too)
- Copy paste the text below.
- Click after the first or second lines.
- Caret will be in incorrect position.

```
I strove with none, for none was worth my strife;
It sinks and I am ready to depart
O farther, farther sail!
```

**Comment by jmatth** [comment] 2022-09-30 16:29
This is a duplicate of #549, which has an ongoing PR at #602.

**Comment by Mijawel** [comment] 2022-10-01 13:24
thanks for the heads up!

**Comment by matthew-carroll** [comment] 2022-10-01 21:27
Closing as duplicate.

**Closed by matthew-carroll** 2022-10-01 21:27 UTC
