### ISSUE TITLE
TypeErrorImpl - Unexpected null value. Caused when refreshing webpage (and sometimes resizing)

### ISSUE THREAD

**Issue by Mijawel** [superlistapp/super_editor#781] opened 2022-09-14 04:43 UTC
Receiving the following error and typing no longer works (the caret just moves around wildly). I have also seen the same error appear in a few other contexts including with page resizing although it has been harder to replicate. (With the method below I have managed to replicate it more reliably).

```
Exception caught by scheduler library
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/super_editor/src/default_editor/document_caret_overlay.dart 112:79       [_updateCaretOffset]
packages/super_editor/src/default_editor/document_caret_overlay.dart 92:7         <fn>
packages/flutter/src/scheduler/binding.dart 1146:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1091:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 997:5                                 [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1090:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 160:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 194:45                                     <fn>
```

How to replicate:
1. Run the code
2. Type a few words.
3. Refresh page
4. Type a bit more
5. Refresh page
6. Bug should appear (if not refresh again)

```
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final myDoc = MutableDocument(
    nodes: [
      ParagraphNode(
        id: DocumentEditor.createNodeId(),
        text: AttributedText(text: 'This is a header'),
        metadata: {
          'blockType': header1Attribution,
        },
      ),
      ParagraphNode(
        id: DocumentEditor.createNodeId(),
        text: AttributedText(text: 'This is the first paragraph'),
      ),
    ],
  );

  DocumentEditor? docEditor;


  @override
  Widget build(BuildContext context) {
    docEditor ??= DocumentEditor(document: myDoc);

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SuperEditor(
        editor: DocumentEditor(document: myDoc),
      ),
    );
  }
}
```

Video of error:

https://user-images.githubusercontent.com/52743180/190058861-f80019fb-a754-4c30-afd2-2d72adb1ea77.mov

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by matthew-carroll** [comment] 2022-10-01 21:42
@Mijawel does this issue happen when running in production, or only when you're running in debug mode and connected to Flutter's debugger? In other words, is this a hot restart issue, or a perpetual issue with `SuperEditor`?

**Comment by angelosilvestre** [comment] 2022-10-09 18:48
@Mijawel Could you please try again on the latest main and see if the issue is still happening? I tried your example but I couldn't reproduce the issue.

**Comment by matthew-carroll** [comment] 2022-10-17 21:29
We haven't received any clarification to our questions in over two weeks. I'm going to close this ticket. If the issues persists, please open a new ticket with appropriate reproduction steps and description.

**Closed by matthew-carroll** 2022-10-17 21:29 UTC
Labels: bounty_junior
