### ISSUE TITLE
[SuperTextField] On mac, IME panels don't react to keyboard interactions if Actions is used

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1583] opened 2023-11-03 12:30 UTC
Steps to reproduce:
* Use `Actions` as an ancestor of `SuperTextField` and specify the behavior for `DismissIntent` and `ActivateIntent` (other intents are probably valid as well, but didn't explore any further)
```dart
...
Actions(
  actions: {
    DismissIntent: CallbackAction(
      onInvoke: (intent) {
        print('DismissIntent invoked');
      },
    ),
    ActivateIntent: CallbackAction(
      onInvoke: (intent) {
        print('ActivateIntent invoked');
      },
    ),  
  },
  child: SuperTextField(
...
```
* Run the interactive demo for `SuperTextField`
* Place the selection somewhere in text
* Interact the one of the IME panels (e.g. accent panel when using German or Portuguese keyboard layouts, or Japanese for the character conversion panel)
* Press ENTER or ESCAPE

**Expected:** the panel closes and the composition is cancelled
**Actual:** nothing happens (panel remains open) aside from the print statements in the code snippet above

**Comment by matthew-carroll** [comment] 2023-11-03 18:23
@miguelcmedeiros at first glance this looks like expected behavior. You're intercepting the actions, right? Which means you get your print statement, but the default OS behavior doesn't execute. Is there any reason to believe that you should be able to respond to `onDismiss()` while simultaneously having that key press flow to the OS? 

Also, I'm assuming this is Mac, but please be sure to specify which platform you're running on for each bug.

**Comment by matthew-carroll** [comment] 2023-11-03 20:06
@knopp after conversation with @miguelcmedeiros it sounds like Miguel is looking for an OS selector behavior that's currently not possible in Flutter, and we're wondering if this is something you could raise with the Flutter team.

In the case of this ticket, Miguel would like to register an `Actions` widget above `SuperTextField`, so that his action callbacks run when the user presses certain keys, like `ESC` to "dismiss". But, Miguel ALSO wants the standard OS selector to run. Continuing with the example, if an Emoji picker is open and the user presses `ESC`, Miguel's callback gets invoked AND the OS dismisses the Emoji picker window.

I believe that currently we are forced into one direction or the other. Either an `Action` responds to a key press, and thereby prevents it from reaching the OS, or absolutely no `Action` on the Flutter side responds and the key press bubbles up to the OS and triggers a selector.

Based on your selector work, does my description here sound correct? If so, what do you think about helping the Flutter team to alter their key press event system so that at least some type of actions are able to run in response to the same key press that triggers an OS selector?

**Comment by knopp** [comment] 2023-11-03 20:18
Reading from the description, I don't think @miguelcmedeiros wants `ESC` to both dismiss the IME selector window and trigger the action. That's wouldn't be possible, since the `NSTextInputContext` eats the enter/escape keys when popover is IME dismissed/confirmed.

If I'm reading it correctly, the issue is that enter and escape does't close the IME selection popover. The code above should work with flutter `TextField` and I assume the expectation here is that it works with `SuperTextField` as well.

The way this normally works in Flutter is that on macOS you register a `Shortcut` for `ESC` and `ENTER` in the text field with `doNothingAndStopPropagationIntent` and then also translate the appropriate IME selectors  to `DismissIntent` and `ActivateIntent`. That's how it is done in FlutterTextField. 

so the `DismissIntent` and `ActivateIntent` keep working on macOS, but instead of being triggered from a shortcut, the are triggered from text input plugin selector.

It's a bit unfortunate that platform abstraction leaks like this in Flutter but it's a tough problem to solve.

**Comment by matthew-carroll** [comment] 2023-11-03 20:55
@knopp let me know if I understand you correctly - You're suggesting that within `SuperTextField` we explicitly look for ESC and ENTER and when those keys are pressed, `SuperTextField` should pretend that it's Mac OS and dispatch selectors for DISMISS and NEWLINE?

**Comment by knopp** [comment] 2023-11-03 23:44
I'm suggesting that on SuperTextField will
1) on MacOS add `Shortcut` that handle `ESC` and `ENTER` mapping them to `DoNothingAndStopPropagationIntent`. This is necessary for IME to receive the keyboard events.
2) handle the `cancelOperation:` selector (`performSelector`) turning it into a `DismissIntent` (i.e. `Actions.invoke(primaryFocus?.context, DismissIntent())`);
3) Enter should be handled in `performAction`. Not sure what the default action for `SuperTextField` is, but if unhandled it could send it to primary focus as `ActivateIntent`, see 2)

**Comment by matthew-carroll** [comment] 2023-11-03 23:59
> on MacOS add Shortcut that handle ESC and ENTER mapping them to DoNothingAndStopPropagationIntent. This is necessary for IME to receive the keyboard events.

Based on this statement, then my original description of the problem is accurate, right? Flutter is handling the key press, and therefore it's not bubbling up to the OS, and therefore the OS isn't generating a selector. Is that right?

If that's right, then my earlier question about a Flutter change still stands. If the crux of the issue is that when Flutter reports a key as "handled", the OS doesn't receive the key, can't Flutter be changed to give developers an option to react to a key press without reporting it as "handled", thereby allowing Flutter handlers AND the OS to respond to the same key press?

> handle the cancelOperation: selector (performSelector) turning it into a DismissIntent (i.e. Actions.invoke(primaryFocus?.context, DismissIntent()));

We can do this, but how does this relate to Miguel's reported problem?

> Enter should be handled in performAction. Not sure what the default action for SuperTextField is, but if unhandled it could send it to primary focus as ActivateIntent, see 2)

We can do this, too, but like 2, how does this relate to Miguel's posted problem?

**Comment by knopp** [comment] 2023-11-04 00:25
> If that's right, then my earlier question about a Flutter change still stands. If the crux of the issue is that when Flutter reports a key as "handled", the OS doesn't receive the key, can't Flutter be changed to give developers an option to react to a key press without reporting it as "handled", thereby allowing Flutter handlers AND the OS to respond to the same key press?

You can already do that. But what is the point of it? There is no way for the application to determine whether the IME popover is visible, so you shouldn't perform any action on escape or enter, you should only respond to performSelector(cancelOperation) and performAction. You can not know whether the `ENTER` key event that you are getting should close the IME popover or submit text field. 

> 
> > handle the cancelOperation: selector (performSelector) turning it into a DismissIntent (i.e. Actions.invoke(primaryFocus?.context, DismissIntent()));
> 
> We can do this, but how does this relate to Miguel's reported problem?
> 
> > Enter should be handled in performAction. Not sure what the default action for SuperTextField is, but if unhandled it could send it to primary focus as ActivateIntent, see 2)
> 
> We can do this, too, but like 2, how does this relate to Miguel's posted problem?

It will handle it same way as it is handled with Flutter Text field. The intents will work and the IME popovers will work as well. 

Using `DoNothingAndStopPropagationIntent` will ensure that the IME receives `ENTER` and `ESCAPE` events.  That fixes
```
Expected: the panel closes and the composition is cancelled
Actual: nothing happens (panel remains open) aside from the print statements in the code snippet above
```

Forwarding the selector and action as intents as described will ensure that the actions in example snippets will work as expected.

**Comment by matthew-carroll** [comment] 2023-11-04 00:31
> You can already do that. But what is the point of it?

The point is to answer Miguel's original post. If you look at his example, he said he wanted to run some kind of action `onDismiss()` at the same time that the popover is dismissed. The post didn't include a reason why. You'll have to ask him. If the actual goal is something other than what's in the original issue ticket, I would encourage one of you to update it with the actual goal.

> Using DoNothingAndStopPropagationIntent will ensure that the IME receives ENTER and ESCAPE events. That fixes

As far as these other changes related to dispatching intents from `SuperTextField`, we first need to decide how app developers are meant to control these things. Both of you may recall that the reason we created `SuperTextField` was because Flutter kept making decisions inside of `TextField` that app developers didn't want them to make. We don't want to repeat that here. I believe that app developers probably should be able to take any action they'd like when the user presses ENTER or ESC or any other key. Therefore, I'd like for us to identify an appropriate place to make such decisions configurable.

In fact, if all of this comes down to simply doing something when the user presses ENTER or ESC, why doesn't the existing key handler system let you do that? Why do we need additional behavior in `SuperTextField`?

**Comment by knopp** [comment] 2023-11-04 00:54
> The point is to answer Miguel's original post. If you look at his example, he said he wanted to run some kind of action `onDismiss()` at the same time that the popover is dismissed. The post didn't include a reason why. You'll have to ask him. If the actual goal is something other than what's in the original issue ticket, I would encourage one of you to update it with the actual goal.

I don't think those intents are meant to be fired on IME popover dismissal. They are there to demonstrate the problem. Without intents presents the `ShortcutManager` will not mark the key event as handled and thus the IME popover issue will not be reproduced.

I think we should wait for @miguelcmedeiros follow-up.

**Comment by miguelcmedeiros** [comment] 2023-11-07 18:49
> I don't think those intents are meant to be fired on IME popover dismissal. They are there to demonstrate the problem.

Correct. The expectation is that those intents would not be handled in the `Actions` widget that is part of the code snippet, since I would assume that `super_editor` would have handled those intents and not let it bubble up.

**Comment by matthew-carroll** [comment] 2023-11-07 19:12
My understanding is that we have code like this:

Mac OS (where selectors run)
  MaterialApp
    Scaffold
      Bunch of widgets
        SuperTextField (has key focus)

For ENTER or ESC to generate a selector, that event must bubble all the way from `SuperTextField`, up past `MaterialApp`, and then be received by the operating system.

So I'm confused as to why the expectation is that bubbling doesn't happen. The operating system is the top-most recipient for a key event. Am I missing something?

**Comment by knopp** [comment] 2023-11-07 19:32
```dart
Actions(
  actions: {
    DismissIntent: CallbackAction(
      onInvoke: (intent) {
        print('DismissIntent invoked');
      },
    ),
  },
```

This prevents the event from bubbling. But it's not the `Action` itself, it is the shortcut defined in material app. That's why flutter text fields declares additional `Shortcut`, which maps `escape` into `DoNothingAndStopPropagatonIntent`, which ensures that the event skips other `Shortcuts` above it and goes to the operating system.

**Comment by matthew-carroll** [comment] 2023-11-07 19:40
Ok. It's worth noting a couple things here. First, this situation is a combination of two unfortunate things:

1. Apparently on this one particular operating system, there's a special communication path that doesn't exist on any other OS.
2. Flutter thought it would be cool to automatically do a bunch of shortcut stuff that requires careful and explicit overrides to effectively opt out.

For these reasons, I want to make sure that we don't bake too much into`SuperTextField`. As I mentioned in an earlier comment, the whole reason we built `SuperTextField` was because Flutter simply wouldn't stop adding random stuff into `TextField`, which you couldn't remove or turn off or opt out of. We don't want to repeat that.

First, I'll point out, if adding an `Actions` widget with an override is all it takes to solve this problem, all users of `SuperTextField` are capable of doing that, right? If I understand correctly, this isn't technically a blocker, it's just an unexpected result that requires adding another widget to get the behavior you want. This doesn't mean we shouldn't do anything in `SuperTextField`, I just want to be explicit that simple widget composition should solve this problem for you.

Second, if we're going to change `SuperTextField` then it's important we identify a reasonable place and way to make this decision configurable. It shouldn't be forced on all users.

**Comment by knopp** [comment] 2023-11-07 19:43
Adding the `Action` is only one part of fix. That can be done above text field.
 Second part is handling the selector and turning it into an Intent. This cannot be done by users.

**Comment by matthew-carroll** [comment] 2023-11-07 19:46
Now I'm confused again. I thought we were talking about trying to get the ESC key to the OS. But if we're already receiving a selector then that means the OS already got the key, mapped the key to a selector, and then sent the selector to the IME....I still don't understand what the problem is...

**Comment by knopp** [comment] 2023-11-07 19:49
We're not receiving the selector. Not when the text field is surrounded by action. We will start receiving the selector once there is `Shortcut` in place that maps `ESC` into `DoNothingAndStopPropagationIntent`.

Once the shortcut is added and we're getting the intent, we need to make sure that the `Actions` above works as expected. That means translating the `cancelOperation:` selector into intent:
```dart
Actions.invoke(primaryFocus?.context, DismissIntent()))
```

**Comment by matthew-carroll** [comment] 2023-11-07 20:00
Unfortunately, I can't follow these explanations. I'm having difficulty understanding what's happening now vs what you want to happen. It sounds like there may be details about selector generation that I don't understand, but I can't tell if that's the case or not. For example, it sounds like you just implied that a Flutter `Intent` can result in an OS selector generation, but that's news to me, and I'm also not sure if I understood you correctly.

I think I'm going to need a very clear description of events as they happen now vs the series of events you want to see. For example, you might start with a description like this:

```
User presses ESC
  ESC is reported to SuperTextField handlers
    SuperTextField handlers don't handle it
      ESC bubbles to MaterialApp, is handled by converting ESC to a [insert intent here]
        [insert intent here] causes [insert unwanted effect]
```

I don't know if the above is accurate. If it is, I don't know which intent is being generated right now or what the side effect is. One of you can correct that description of existing behavior, and/or insert the missing info.

Then, you could describe a similar series of events that demonstrate what you would like to happen.

Perhaps then I'll understand the problem and the suggested solution.

**Comment by knopp** [comment] 2023-11-07 20:28
This is what happens with Flutter Textfield on macOS
```
User presses ESC
  ESC doesn't bubble to Material app. Instead it is caught by Shortcuts inside TextField, where it gets mapped into `DoNothingAndStopPropagationIntent`.
    ESC bubbles to directly to NSTextInputContext, skipping all other Flutter Shortcuts (because of DoNothingAndStopPropagationIntent)
       NSTextInputContext generates cancelOperation: selector
          Flutter TextField catches the cancelOperation: selector, turning it into a DismissIntent, letting the actions above text field handle this intent
```

To turn the selector into an intent, the TextField does something like this:
```dart
Actions.invoke(primaryFocus?.context, DismissIntent()))
```

This lets the actions above, which would normally be triggered by ESC Shortcut, be triggered from `cancelOperation:` selector instead. (Necessary because we blocked ESC in second line).

**Comment by matthew-carroll** [comment] 2023-11-07 21:24
Your 2nd and 3rd lines are contradictory. Either the event is handled, or it bubbles. Either the text field responds and squashes the event, or the event keeps moving up the tree, and eventually reaches the top of the tree.

Also, you didn't include a description of events as they are happening now. I'd really like to see the current series of events vs the desired series of events.

**Comment by knopp** [comment] 2023-11-07 21:33
> Your 2nd and 3rd lines are contradictory. Either the event is handled, or it bubbles. Either the text field responds and squashes the event, or the event keeps moving up the tree, and eventually reaches the top of the tree.

How so? There is also `KeyEventResult.skipRemainingHandlers`, which is what `DoNothingAndStopPropagationIntent` does and which skips all remaining Flutter handles letting the native code handle event.

> 
> Also, you didn't include a description of events as they are happening now. I'd really like to see the current series of events vs the desired series of events.

I described how events are happening when using Flutter Text field. With SuperTextField I'd assume it's something like this.

```
User presses ESC
 ESC bubbles up from SuperTextField, up to Shortcut widget, which handles the event because there is Action mapped to ESC. 
 Because ESC was handled, it doesn't reach the NSTextInputContext and the IME selection can not be cancelled.
```

**Comment by matthew-carroll** [comment] 2023-11-07 22:48
I'm not sure we're going to be able to clarify this via GitHub. @miguelcmedeiros should we schedule a call with you and me, or possibly all three of us, to more quickly drill down the relevant behaviors?

**Comment by matthew-carroll** [comment] 2023-11-09 00:05
We spoke on a call today. Here's some further information.

Superlist has the following situation:

SidePane
  Actions (dismisses on ESC)
    Message SuperTextField (doesn't handle ESC)

When `SuperTextField` has focus, and an IME panel is open, presses ESC, rather than closing the IME panel, it closes the pane.

Note: Technically we weren't able to reproduce the above result in the app. This was probably due to some other bug in that field. But the above situation describes the problem.

It's possible that this same issue exists in `SuperEditor`. We should verify and fix, if necessary.

The reason this issue doesn't happen with a regular Flutter `TextField` is that the `TextField` instructs the ESC key press to ignore and skip all remaining handlers. This results in the OS receiving the ESC key, which generates a selector. The selector is received by the `TextField`, then the `TextField` dispatches a dismiss intent.

There are two separate but related issues for `SuperTextField`:

- `SuperTextField` needs to mark the ESC key ignored and to skip all remaining handlers, so that a selector is generated. This will dismiss the IME popover.
- `SuperTextField` needs to let clients react to dismiss selectors, because otherwise only the internals of `SuperTextField` are able to react to that selector. The right answer here might be to offer a callback that reports all selectors.

**Closed** 2023-11-14 21:58 UTC
Labels: area_supertextfield, f:superlist
