### ISSUE TITLE
Certain characters don't work in Supereditor (^`´)

### ISSUE THREAD

**Issue by MarcelKaeding** [superlistapp/super_editor#385] opened 2022-01-07 13:11 UTC
Steps to reproduce:
- us a physical non-US keyboard 
- focus on a text field
- use the physical keys on your keyboard 
- try to enter ^ or ` or ´ with special keys found on non-us keyboards
- input does not work, no character is shown

**Comment by matthew-carroll** [comment] 2022-02-03 06:34
@MarcelKaeding I just opened up the `SuperTextField` desktop demo and typed in `^` and "`". Can you provide more specific reproduction steps?

**Comment by matthew-carroll** [comment] 2022-02-17 06:21
@miguelcmedeiros can you investigate this issue on your end? I can't seem to create this issue on my keyboard, but you seemed to be able to repro the issue on yours. Can you see if you're able to figure out what the root cause might be?

**Comment by MarcelKaeding** [comment] 2022-02-17 17:06
When running the example project on MacOS and trying to enter ^`´ I'm getting these errors in the terminal

flutter: [document_keyboard_actions.dart] - deleteExpandedSelectionWhenCharacterOrDestructiveKeyPressed: Running...
IsMenuKeyEvent: found no unichar data in event; retranslated without deadkeys to produce '^'

flutter: [document_keyboard_actions.dart] - deleteExpandedSelectionWhenCharacterOrDestructiveKeyPressed: Running...
IsMenuKeyEvent: found no unichar data in event; retranslated without deadkeys to produce '`'

flutter: [document_keyboard_actions.dart] - deleteExpandedSelectionWhenCharacterOrDestructiveKeyPressed: Running...
IsMenuKeyEvent: found no unichar data in event; retranslated without deadkeys to produce '´'

**Comment by matthew-carroll** [comment] 2022-02-18 08:44
@MarcelKaeding I'll probably need to pair program a solution with @miguelcmedeiros so that there's some way to reproduce the issue while I'm working on it. My keyboard doesn't have this problem. I'm able to insert these characters without issue.

I'm going to move this ticket into the next milestone because it's not mobile-specific and it requires some coordination for us to figure this out.

**Comment by bk-one** [comment] 2022-03-18 19:50
@MarcelKaeding this seems to be fixed, at least I can enter ^ or ` or ´ into a document. Can you please verify?

**Comment by MarcelKaeding** [comment] 2022-03-21 14:38
@bk-one for me it is still the same behavior. getting this errors:

> flutter: INFO: 2022-03-21 15:37:49.362125: Handling key press: RawKeyDownEvent#87fe1(logicalKey: LogicalKeyboardKey#0000a(keyId: "0x140000000a", keyLabel: "", debugName: "Key with ID 0x0140000000a"), physicalKey: PhysicalKeyboardKey#70064(usbHidUsage: "0x00070064", debugName: "Intl Backslash"), repeat: false)
flutter: [document_keyboard_actions.dart] - deleteExpandedSelectionWhenCharacterOrDestructiveKeyPressed: Running...
IsMenuKeyEvent: found no unichar data in event; retranslated without deadkeys to produce '^'

**Comment by bk-one** [comment] 2022-03-21 14:52
I see, seems like we need to get a list of all international keyboard names to fill some blanks in the current keyboard handling

**Comment by bk-one** [comment] 2022-03-22 19:14
waiting for #348

**Comment by matthew-carroll** [comment] 2022-05-18 08:33
@bk-one @MarcelKaeding - Can one of you confirm that this issue is now resolved with the IME merge?

**Comment by MarcelKaeding** [comment] 2022-05-22 18:31
@matthew-carroll see the other issue I just commented on. The app crashes if you press `Return` or any other key, after entering `^` or `´` or ``` or `¨`

**Comment by matthew-carroll** [comment] 2022-05-24 08:27
I'm going to close this issue in favor of this one: https://github.com/superlistapp/super_editor/issues/586

**Closed by matthew-carroll** 2022-05-24 08:27 UTC
Labels: customer_superlist, status_needs_more_info
