### ISSUE TITLE
[BUG] [MacOS + Web] - CMD+Left/Right arrow does not move selection correctly

### ISSUE THREAD

**Issue by brian-superlist** [superlistapp/super_editor#2304] opened 2024-09-04 10:44 UTC
**Package Version**
super_editor, main branch, flutter master.

**User Info**
Superlist

**To Reproduce**
1. On a Mac
2. Update to latest version
3. Run the example app with Chrome
4. Place cursor on the beginning of the line "To get started with your own editing experience, take the following steps:"
5. Press CMD+Right arrow
6. **Expected:** Cursor is placed at the end of the line, **Actual:** Cursor is placed at the beginning of the word "steps"
7. Press CMD+Left arrow
8. **Expected:**, Cursor at beginning of line **Actual:** Cursor at beginning of line (all good!)
9. Press CMD+Left arrow again 
10. **Expected:** Cursor still at beginning of line, **Actual:** Cursor moved to previous line

**Minimal Reproduction Code**
None needed. Example app of super_editor repo.

**Platform**
MacOS + Web

**Flutter version**
Flutter 3.24.0-1.0.pre.565 • channel master • https://github.com/superlistapp/flutter.git

**Comment by angelosilvestre** [comment] 2024-09-20 00:31
> 6. Expected: Cursor is placed at the end of the line, Actual: Cursor is placed at the beginning of the word "steps"

I opened a PR for this.

> 10. Expected: Cursor still at beginning of line, Actual: Cursor moved to previous line

@brian-superlist Are you sure this is the expected behavior? I tested mac desktop and it seems to behave the same way. If this is the expected behavior, should we change it to all platforms (native and web)?

**Comment by brian-superlist** [comment] 2024-10-03 10:21
> Are you sure this is the expected behavior? 

@angelosilvestre I've double-checked apple notes, text edit, chrome or safari text fields, etc. Which apps were you seeing different behavior?

Recording with KeyCastr enabled here: https://github.com/user-attachments/assets/acd24d08-8792-464f-ad3a-ae339a562db0

Option+Arrow - allows moving to a previous / next line
Cmd+Arrow - Does not allow moving to the previous / next line. It simply goes to the beginning / end of the current line.

And yes, you're right, it should be consistent across mac desktop and web.

**Comment by angelosilvestre** [comment] 2024-10-06 23:59
@brian-superlist The only app I'm seeing a different behavior is obsidian, where pressing Cmd + Left Arrow at the beginning of the line moves the caret to the beginning of the paragraph.

https://github.com/user-attachments/assets/6abf94db-e955-472e-b40a-54e6309bed84

Since all other apps show the behavior you mentioned I think it's reasonable to not allow moving to the previous / next line with Cmd + Arrow.

**Closed** 2024-10-18 22:47 UTC
Labels: type_bug, area_supereditor, customer_superlist, bounty_junior, f:superlist, time: 1
