### ISSUE TITLE
[SuperEditor] iOS magnifier flashes, poor visibility, creates additional selection, and toggles toolbar

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1550] opened 2023-10-24 17:11 UTC
This is on the latest stable super_editor stable (https://github.com/superlistapp/super_editor/pull/1546).

https://github.com/superlistapp/super_editor/assets/6467808/fb18cb89-181b-4d63-81da-e5bc72091755

**Comment by Jethro87** [comment] 2023-10-24 17:11
cc @matthew-carroll

**Comment by matthew-carroll** [comment] 2023-10-25 00:20
@angelosilvestre can you remind me what the problems were with the magnifier that caused blinking? I remember that a magnification of 1x was one problem, but looking at Jeff's video, it looks like his blinking magnifier has a higher magnification. Was there also something related to shadows?

**Comment by angelosilvestre** [comment] 2023-10-25 00:23
@matthew-carroll In my tests, when there was a widget with shadows the issue didn't happen.

**Comment by matthew-carroll** [comment] 2023-10-25 00:26
@angelosilvestre can you elaborate? What should @Jethro87 try to root cause the issue? I don't see any flashing the Super Editor demo, so we need to expand the analysis.

**Comment by angelosilvestre** [comment] 2023-10-25 00:40
@matthew-carroll As the previous issue was solved by adjusting the magnification I didn't dig deeper to figure out an explanation to this. But what was happening is that, when placing any widget with shadows in the widget tree, like a FAB or a Material, the blinking stopped.  This isn't a solution, it's just some additional information... 

It might be related to the `RenderBox` pushing a layer for the shadows, but  it will require more investigation.

**Comment by matthew-carroll** [comment] 2023-10-25 00:45
@Jethro87 do you know if you have any widgets with a shadow in your widget tree?

**Comment by Jethro87** [comment] 2023-10-25 02:56
@matthew-carroll The video above was taken in the super_editor example app. I've just tested it again and noticed that the flashing only occurs in the sliver editor example. Both of the following examples are running super_editor stable + Flutter stable (3.13.8) on an iPhone 12.

## Standard editor
https://github.com/superlistapp/super_editor/assets/6467808/4c5f2793-cda9-4f40-baa8-c1ff7e237480

## Sliver editor
https://github.com/superlistapp/super_editor/assets/6467808/645db68c-7e87-4d37-8273-a6643fcccb69

**Comment by matthew-carroll** [comment] 2023-10-25 03:01
@Jethro87 can you try the PR that I posted? I tagged you in it.

**Comment by matthew-carroll** [comment] 2023-10-25 03:17
Also @Jethro87 if the flashing still happens in the PR where I tagged you, can you try on Flutter master with our `main` branch? Maybe Flutter fixed a bug...

**Comment by matthew-carroll** [comment] 2023-10-25 03:24
@Jethro87 Here's what I found with the Sliver example:

SuperEditor `main`, Flutter `master` -> no problem

SuperEditor `stable`, Flutter `master` -> no problem

SuperEditor `stable`, Flutter `stable` -> magnifier flashing and unexpected showing and hiding of overlay controls

This sure seems like a Flutter bug (or two). Please confirm on your end, too.

If it's a Flutter bug, you can file an issue with Flutter, asking them to cherry pick a fix over to stable, or you can wait for the next stable version.

**Comment by matthew-carroll** [comment] 2023-10-25 03:26
@Jethro87 I merged the associated PR, which closed this issue. If aspects of this issue ticket still remain, and they aren't Flutter bugs, please let me know, and we can re-open this ticket.

**Closed** 2023-10-25 03:26 UTC
Labels: area_supereditor, bounty_junior, f:superlist, area_super_reader, time: 5

**Comment by Jethro87** [comment] 2023-10-25 16:23
@matthew-carroll Thanks for digging in. The flickering issue is also not present when using Flutter beta.
