### ISSUE TITLE
Line break doesn't work with bullet list or check boxes

### ISSUE THREAD

**Issue by Biplab-Dutta** [superlistapp/super_editor#1226] opened 2023-07-10 17:46 UTC
When I was playing with the example app, I noticed that the line break key doesn't work in bullet lists and check boxes.
I have attached a video showing the issue.
https://github.com/superlistapp/super_editor/assets/63902683/bd7d7896-47b5-4c7b-b648-8e646a6adbc5

**Comment by angelosilvestre** [comment] 2023-07-19 23:00
It seems this is a duplicate of https://github.com/superlistapp/super_editor/issues/1157

**Comment by angelosilvestre** [comment] 2023-07-30 20:35
I'm closing this as it is already fixed.

**Comment by angelosilvestre** [comment] 2023-07-30 20:35
I'm closing this as it is already fixed.

**Closed by angelosilvestre** 2023-07-30 20:35 UTC
Labels: area_supereditor, bounty_junior, f:superlist, time:2
