### ISSUE TITLE
Fix marketing website compilation errors

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#240] opened 2021-06-06 23:19 UTC
The marketing website still references `SelectableText` rather than `SuperSelectableText`.

Update the references so that CI passes again.

**Comment by salihgueler** [comment] 2021-06-07 08:11
Duplicate of: https://github.com/superlistapp/super_editor/issues/230 ?

**Comment by matthew-carroll** [comment] 2021-06-08 04:01
Looks like it. I'll close #230 because this ticket includes the reason for the build failure.

**Closed** 2021-06-08 05:49 UTC
Labels: area_website, bug
