### ISSUE TITLE
Cannot open drop-down items in editor contextual toolbar

### ISSUE THREAD

**Issue by intonarumori** [superlistapp/super_editor#1451] opened 2023-09-15 08:55 UTC
I'm running super_editor example from the `main` branch, with Flutter on `master` channel and the drop downs in the contextual toolbar don't seem to open.

Please see the attached video:
 
https://github.com/superlistapp/super_editor/assets/86030/a3a79c39-2614-4481-affd-09b57074094e

Let me know if I overlooked something.

**Comment by intonarumori** [comment] 2023-09-15 09:39
Looks like as the button is pressed the editor looses focus and that triggers the hiding of the toolbar.

https://github.com/superlistapp/super_editor/blob/a4da30e67b848548c9e3125086371dad5a2076e7/super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart#L178-L183

But even if I disable that, there's another trigger coming from `Navigator` that will trigger the hiding of the toolbar from `OverlayEntry.remove()`. I'm not that familiar with this aspect of `Navigator` but it looks like pushing a new route on the navigator stack dismisses other overlays.

**Comment by intonarumori** [comment] 2023-09-15 12:41
This finally solved the issue, but now it's of course harder to get rid of the toolbar in general when ex. opening the menu.
```
SuperEditor(
...
  selectionPolicies: SuperEditorSelectionPolicies(
    clearSelectionWhenEditorLosesFocus: false,
    clearSelectionWhenImeConnectionCloses: false,
  ),
...
)
```
Not sure what's worse with the demo, having a sticky toolbar that works, or one that disappears :)

**Comment by manoletre** [comment] 2023-10-04 23:04
I am also having trouble with this

**Comment by matthew-carroll** [comment] 2023-10-14 02:49
@angelosilvestre can you check if this issue is still caused by Flutter's focus behavior, or whether it's something on our end?

**Comment by angelosilvestre** [comment] 2023-10-14 16:53
@matthew-carroll  It seems it's still caused by Flutter. When the dropdown route is pushed, it steals focus from `SuperEditor`. I haven't found a way to prevent that so far.

I think we'll need to, inevitably, build our own `DropDownButton` at some point.

**Comment by matthew-carroll** [comment] 2023-10-14 17:14
@angelosilvestre Thanks. Can you mention the existing issue that we have for this in this ticket and then close this ticket as duplicate?

**Comment by angelosilvestre** [comment] 2023-10-14 17:43
Closing as duplicate of https://github.com/superlistapp/super_editor/issues/731

**Closed by angelosilvestre** 2023-10-14 17:43 UTC
Labels: area_infrastructure, bounty_junior, f:superlist, time: 1
