### ISSUE TITLE
super_editor doesn't use scroll activities, instead scrolls using `.jumpTo()`

### ISSUE THREAD

**Issue by kekland** [superlistapp/super_editor#1465] opened 2023-09-22 07:47 UTC
Hi!

Noticed this when trying to put `super_editor` in a `DraggableScrollableSheet`. Not sure why here: 

https://github.com/superlistapp/super_editor/blob/f471c2435083181a893e1d7278c7c6c27ca5dd69/super_editor/lib/src/default_editor/document_gestures_touch_ios.dart#L827

the scrolling is done with `.jumpTo()`. In order for the scroll to be detectable by `DraggableScrollableSheet` (to allow it to close), I had to modify the scrolling a bit:

```dart
Drag? _drag;

void _onPanStart(DragStartDetails details) {
    final selection = widget.selection.value;
    if (selection == null) {
      _drag = scrollPosition.drag(details, () => _drag = null);
      return;
    }
    
    // ...
}

void _onPanUpdate(DragUpdateDetails details) {
  if (_drag != null) {
    _drag!.update(details);
    _positionToolbar();
    return;
  }

  if (_globalStartDragOffset == null) {
    return;
  }

  // ...
}

void _onPanEnd(DragEndDetails details) {
  if (_drag != null) {
    _drag!.end(details);
    _drag = null;
  } else {
    // The user was dragging a handle. Stop any auto-scrolling that may have started.
    _onHandleDragEnd();
  }
}
```

^ and a similar patch for the Android scroller. While testing, this didn't cause any noticeable issues yet.

I'm not 100% sure that this won't break any other complex positioning things that happen inside of super_editor so I just wanted to know if this looks alright, and if it does, I can open a pull request with changes to `document_gestures_touch_ios.dart` and `document_gestures_touch_android.dart`.

**Comment by rutvik110** [comment] 2023-09-23 03:41
Hey @kekland, thanx for reporting the issue. To better understand this issue, could you please share steps to reproduce it? a reproducible example would also help if you can share.

**Comment by matthew-carroll** [comment] 2023-10-14 02:46
@kekland Flutter's scroll system is very messy. It's unclear to me how one is supposed to plug in to a broader scrolling interaction. You mentioned scroll activities, specifically. Is there any documentation around how something like `SuperEditor` would be expected to interact with those ancestor scrollables?

**Comment by matthew-carroll** [comment] 2023-12-09 01:19
@kekland do you have any further info or input based on my above comment?

**Comment by matthew-carroll** [comment] 2023-12-13 05:55
I'm closing this due to non-response.

**Closed by matthew-carroll** 2023-12-13 05:55 UTC
Labels: awaiting-customer-feedback
