### ISSUE TITLE
Mouse Scrolling Highlights Text and Depends on Mouse Position (Mac OS only)

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#873] opened 2022-11-29 20:36 UTC
We are seeing this behavior with our SE implementation on the Mac OS platform only.  Depending on the position of the mouse, the document can be scrolled only so far with the mouse scroll wheel (or track pad).  If you position the mouse in the middle of the document, the document will not scroll up or down. It will only go up or down if the mouse is placed sufficiently close to the upper or lower boundary of the document.  Additionally, as you are scrolling text is highlighted.

https://user-images.githubusercontent.com/37011672/204641898-1fc097a5-baef-472d-904d-2ee08a5ed8a0.mp4

**Comment by matthew-carroll** [comment] 2022-12-23 05:27
@transcendr can you provide a minimal reproduction, or let us know how to recreate this problem with the example app?

**Comment by transcendr** [comment] 2022-12-29 22:37
Hi @matthew-carroll  thank you for your reply. We'll try and get this to you in the coming week.

**Comment by transcendr** [comment] 2023-01-19 09:42
@matthew-carroll  was looking to get this to you asap, apologies, we had some prio's come up. I'm looking for the simplest way to set up that repro.  Thanks!

**Comment by angelosilvestre** [comment] 2023-01-31 21:35
@transcendr Which `super_editor` version are you using? This issue seems to be solved after version `0.2.3`

**Comment by matthew-carroll** [comment] 2023-08-29 06:54
@transcendr can you please let us know if this is still an issue? If so, please provide a minimal repro. If not, let's close the ticket.

**Comment by matthew-carroll** [comment] 2023-12-13 05:58
Closing due to non-response.

**Closed by matthew-carroll** 2023-12-13 05:58 UTC
Labels: awaiting-customer-feedback
