### ISSUE TITLE
Paste Does Not Work (Firefox)

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#881] opened 2022-12-07 12:51 UTC
On Firefox, paste functionality does not work.  On Edge and Chrome, this is not an issue. Also, copy and cut are working as expected, so it appears as it's only paste that is not functional.

**Comment by jmatth** [comment] 2022-12-07 18:18
This is a duplicate of #395. The root cause is that Firefox puts restrictions on clipboard access that make Flutter's [`Clipboard.getData`][1] not work. Flutter's default text fields work around the issue with some relatively complex trickery to manipulate contenteditable HTML elements into focus to keep Firefox happy. It's not clear if it's possible to implement something similar outside the engine, and if it is it won't be a simple fix.

[1]: https://api.flutter.dev/flutter/services/Clipboard/getData.html

**Comment by matthew-carroll** [comment] 2023-08-29 06:52
Based on the comment from @jmatth I'm going to close this as a duplicate.

**Closed by matthew-carroll** 2023-08-29 06:52 UTC
