### ISSUE TITLE
[marketing website]: fix Netlify build

### ISSUE THREAD

**Issue by roughike** [superlistapp/super_editor#230] opened 2021-06-04 08:22 UTC
The Netlify build is currently broken, which means that any new commits to the marketing website on the main branch will not propagate to the marketing website.

**Comment by matthew-carroll** [comment] 2021-06-05 05:10
Can you provide the relevant info about what's broken and what the desired resolution should be?

**Comment by matthew-carroll** [comment] 2021-06-08 04:02
Closing this ticket in favor of #240, which includes the cause of the build failure.

**Closed by matthew-carroll** 2021-06-08 04:02 UTC
Labels: question
