### ISSUE TITLE
[web] [bug] Pressing return when entering a hyperlink removes selected text

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#183] opened 2021-05-14 17:23 UTC
Using Chrome latest (90.0.4430.212).

Steps to reproduce:

- Start the sample editor (Editor Demo) for web
- Mark any word or sequence of characters
- Press the hyperlink icon
- Type in any link
- Hit return/enter

The marked word is removed.

Edit: this is working fine on MacOS.

**Comment by matthew-carroll** [comment] 2022-07-10 00:25
Try to solve this after #609 is solved.

**Comment by matthew-carroll** [comment] 2023-08-16 01:20
@angelosilvestre can you check whether this issue is still happening?

**Comment by angelosilvestre** [comment] 2023-08-16 01:35
@matthew-carroll I tested and it doesn't seem to be happening.

**Comment by matthew-carroll** [comment] 2023-08-16 01:36
Thanks. I'll close this as complete.

**Comment by hillelcoren** [comment] 2023-12-07 10:57
Since upgrading to Flutter 3.16.2 this problem has reappeared on Windows.

**Comment by matthew-carroll** [comment] 2023-12-07 22:26
Re-opening per @hillelcoren 's comment. @angelosilvestre can you please take a look?

@hillelcoren which version of Super Editor are you using?

**Comment by angelosilvestre** [comment] 2023-12-08 13:01
@hillelcoren Is there a specific sequence of steps or a specific `SuperEditor` configuration needed to trigger the issue? I'm not being able to reproduce it.

**Comment by hillelcoren** [comment] 2023-12-08 13:30
I'm following the steps listed above.

**Closed** 2023-12-13 01:36 UTC
Labels: type_bug, area_supereditor, bounty_junior, f:superlist, time:2
