### ISSUE TITLE
magnifier magnifies the wrong area

### ISSUE THREAD

**Issue by BazinC** [superlistapp/super_editor#1957] opened 2024-04-22 10:20 UTC
**Package Version**
stable or main branch

**To Reproduce**
On ios, long press on text to display magnifier. 

**Actual behavior**
See video below. simulator (iPhone 15 iOS 17.0) running super editor example. magnified area is off. It looks like it magnifies the content below the cursor.

[supereditor ios magnifier.webm](https://github.com/superlistapp/super_editor/assets/6229343/de218bc7-7fb4-41d9-b648-140ccb1897b4)

**Expected behavior**

[native ios magnifier.webm](https://github.com/superlistapp/super_editor/assets/6229343/895f63b4-525e-4f92-91a8-b40243ea2377)

Same with Android simulator (Pixel 7 Pro API 32):
![Screenshot_1713780723](https://github.com/superlistapp/super_editor/assets/6229343/77effa40-f1a6-49b2-8c56-3a0a03e7bdd8)

**Platform**
iOS and Android

**Flutter version**
3.19.1

**Additional context**
I suggest the super_editor default magnifier to use or take inspiration from Flutter CupertinoTextMagnifier/TextMagnifier

**Comment by angelosilvestre** [comment] 2024-04-30 01:22
@BazinC Are you using some specific settings to trigger this issue on Android? I was able to reproduce it on iOS only.

**Comment by BazinC** [comment] 2024-05-02 09:52
@angelosilvestre For Android I'm just running the demo app, from stable branch, on an Android Simulator (Pixel 7 Pro API 32).
I don't have a physical Android device with me right now. I can try later when I have one.

<img width="1721" alt="image" src="https://github.com/superlistapp/super_editor/assets/6229343/99008ca6-0539-4b97-9a6f-40e06e8fe699">

**Comment by matthew-carroll** [comment] 2024-05-07 03:04
@angelosilvestre @BazinC - It looks like we're seeing unpredictable API level problems for Android:

 - Pixel 7 Pro emulator, API 32: The magnification region is too low
 - Pixel 7 Pro emulator, API 33: The magnification region is correct
 - Pixel 7 Pro emulator, API 34: The magnification region is too low

**Comment by angelosilvestre** [comment] 2024-05-09 00:39
For the Pixel 7 Pro emulator, the `devicePixelRatio` is 3.5, and `Offset(0, -22 * MediaQuery.of(context).devicePixelRatio)` doesn't produce correct results:

![image](https://github.com/superlistapp/super_editor/assets/7597082/20d9259f-a687-483f-b3b6-c804470b9f07)

The expression produces `-77.0` while the value to magnify the correct area is `-45`, where `45 / 3.5 ~= 13`.

**Comment by angelosilvestre** [comment] 2024-05-09 00:44
@matthew-carroll If we just do `-150 / pixelRatio` it seems to produce the correct results. `-150` is the follower offset.

**Comment by BazinC** [comment] 2024-05-15 17:30
@matthew-carroll I suggest you reopen the ticket since it is not fixed on ios.
The ios fix seems to be implemented in this PR https://github.com/superlistapp/super_editor/pull/1973 
cc @angelosilvestre

**Comment by angelosilvestre** [comment] 2024-05-18 22:02
@matthew-carroll Should this be closed now that https://github.com/superlistapp/super_editor/pull/1973 is merged?

**Comment by matthew-carroll** [comment] 2024-05-18 22:32
I think so.

**Closed by matthew-carroll** 2024-05-18 22:32 UTC
Labels: type_bug, area_supereditor, area_supertextfield, bounty_junior, time:2, area_super_reader, f:clickup
