### ISSUE TITLE
[SuperTextField] [iOS] [Android] maxLines not respected on mobile

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#505] opened 2022-03-30 23:49 UTC
## Steps to reproduce

Code:
```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.black,
            child: const SuperTextField(
              lineHeight: 16,
              maxLines: 3,
            ),
          ),
        ),
      ),
    );
  }
}
```

- Run the app
- Tap black rectangle (the text field)
- Type more than 1 line of text to get the text to wrap

## Actual behavior
While typing, the text field stays the height of 1 line.

https://user-images.githubusercontent.com/220686/160948325-c40b394d-2a58-4a09-9b23-2e49e6513a44.mp4

## Expected behavior
The text field should grow to the height of 2 lines

## Platform
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

CC @lucasarcouto who found and documented the original issue

**Comment by matthew-carroll** [comment] 2022-07-10 00:31
Ideally, we'd like to have an IME simulator to implement the tests for this ticket. An IME simulator is in the works in `flutter_test_robot` but is currently blocked by Flutter.

**Comment by angelosilvestre** [comment] 2023-09-05 00:35
@matthew-carroll I tested with the provided sample code and it seems to be working.

**Comment by matthew-carroll** [comment] 2023-09-05 04:08
Thanks. Closing as can't reproduce.

**Closed by matthew-carroll** 2023-09-05 04:08 UTC
Labels: area_supertextfield, bounty_junior, f:superlist, time: 1
