### ISSUE TITLE
Emojis are counted as too many characters, affecting the offsets of attributions

### ISSUE THREAD

**Issue by roughike** [superlistapp/super_editor#442] opened 2022-02-19 10:38 UTC
When a paragraph starts with an emoji, and the entire (non-emoji) text has been attributed with for example `boldAttribution`, the `AttributedText` has unexpected values.

For example, with a paragraph with the contents `💌 hello world`, and trying to make only `hello world` bold, we get the following:

```
flutter: [TextNode] - text: [AttributedText] - "💌 hello world"
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 3, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 13, type: SpanMarkerType.end, metadata: {}
 ```

**Expected behavior:** start offset for bold attribution is 2, end offset is 12
**Actual behavior:** start offset for bold attribution is 3, end offset is 13

If I switch the emoji to something else, for example `🙆‍♀️ hello world`, and trying to make only `hello world` bold, the start offset becomes different:

```
flutter: [TextNode] - text: [AttributedText] - "🙆‍♀️ hello world"
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 6, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 16, type: SpanMarkerType.end, metadata: {}
```

**Expected behavior:** start offset for bold attribution is 2, end offset is 12
**Actual behavior:** start offset for bold attribution is 6, end offset is 16

The bug can be verified by copy-pasting the example strings in a given SuperEditor and printing the contents of each node every time the document changes:

```dart
_document.addListener(() {
  for (final node in _document.nodes) {
    print(node);
  }
});
```

**Comment by osaxma** [comment] 2022-02-19 11:28
By the way, this is not a bug -- it's just how `String` works. The offset is based on the number of UTF-16 code units in the given string. And emojis, especially skin emojis, can have several ones:  

```dart
void main() {
  print('💌'.length); // prints 2 
  print('🙆‍♀️'.length); // prints 5
}
```

The [characters](https://pub.dev/packages/characters#unicode-characters-and-representations) package has further and better explanation in its readme.

**Comment by roughike** [comment] 2022-02-19 11:44
> @osaxma: By the way, this is not a bug -- it's just how String works.

Do you mean:
* SuperEditor is currently working as expected, and the `SpanMarker`s are properly positioned as is, or
* Dart's `String` is working currently as expected, but SuperEditor should adjust the `SpanMarker`s based on the grapheme clusters, not code units?

If it's the former, I would be a bit surprised and would want to know why - in #434, a related (but different) bug was also fixed by using the `characters` package.

If it's the latter, then we're on the same page :-)

**Comment by roughike** [comment] 2022-02-21 23:41
Had a chat with one team member and this might be working as intended after all.

**Comment by bk-one** [comment] 2022-02-28 10:28
Let's chat about this in our JF, @matthew-carroll. I would like to discuss if there are reasons not to use a package like https://pub.dev/packages/characters to make sure we have offsets in characters and not in bytes.

**Comment by roughike** [comment] 2022-03-01 10:59
@matthew-carroll As discussed in today's call, here's how an opt-in API could look like, with fake documentation and made up method names:

**lib/src/core/document.dart:**
```dart
abstract class Document with ChangeNotifier {
  ...

  /// Returns a copy of this [Document], but with all start and end offsets based 
  /// on user-visible characters.
  ///
  /// By default, if the document contains a [ParagraphNode] with the contents
  /// of "🙆‍♀️ hello", and the user wants to make "hello" bold, the start offset for 
  /// the [boldAttribution] would be `6`. This happens because the start and end
  /// offsets in [AttributedText] are counted with [String.length], which counts 
  /// code units instead of user visible characters (=grapheme clusters).
  ///
  /// With the previous example, this method would return a [Document] where
  /// the start offset for the [boldAttribution] would be `2`, where the emoji and 
  /// the whitespace between the emoji and "h" would be counted as one 
  /// character each.
  Document withOffsetsBasedOnUserVisibleCharacters();

  /// Returns a copy of this [Document], but with all start and end offsets based 
  /// on code units instead of user-visible characters. 
  ///
  /// If the start and end offsets are already based on counting code units, the 
  /// resulting document will be identical to the current one.
  /// 
  /// Does the reverse of [withOffsetsBasedOnUserVisibleCharacters].
  Document withOffsetsBasedOnCodeUnits();
}
```

We added two extra method in the already existing `Document` class that both return a copy of the document.

For example, let's say a user of SuperEditor is persisting their document with a class called `MyDocumentPersistence`. It's overly simplified on purpose:

```dart
class MyDocumentPersistence {
  Future<Document> getDocument() async {
    // Gets a previously persisted document. Details don't matter.
  }

  Future<void> persistDocument(Document document) async {
    // Persists the given document. Details don't matter.
  }
}
```

And the OLD client code looking something like this:

```dart
final _myDocumentPersistence = MyDocumentPersistence();

...
class _ExampleState extends State<Example> {
  late final DocumentEditor _editor;

  @override
  void initState() {
    super.initState();
    _openDocument();
  }

  void _openDocument() async {
    final document = await _myDocumentPersistence.getDocument();
    _editor = DocumentEditor(document: document);
    _editor.document.addListener(_handleDocumentChanged);
  }

  void _handleDocumentChanged() {
    final document = _editor.document;
    _myDocumentPersistence.persistDocument(document);
  }
  ...
}
```

The NEW client code would be:

```dart
final _myDocumentPersistence = MyDocumentPersistence();

...
class _ExampleState extends State<Example> {
  late final DocumentEditor _editor;

  @override
  void initState() {
    super.initState();
    _openDocument();
  }

  void _openDocument() async {
    final document = await _myDocumentPersistence.getDocument();

    // NEW: added ".withOffsetsBasedOnCodeUnits()"
    _editor = DocumentEditor(document: document.withOffsetsBasedOnCodeUnits());
    _editor.document.addListener(_handleDocumentChanged);
  }

  void _handleDocumentChanged() {
    // NEW: added ".withOffsetsBasedOnUserVisibleCharacters()"
    final document = _editor.document.withOffsetsBasedOnUserVisibleCharacters();
    _myDocumentPersistence.persistDocument(document);
  }
  ...
}
```

I think for this to work, we need both `.withOffsetsBasedOnCodeUnits()` and `.withOffsetsBasedOnUserVisibleCharacters()`.

Otherwise, a previously persisted document that has offsets based on user-visible characters wouldn't render properly when opening it.

## Alternatives

### Have this as the only possible behavior
SuperEditor would adjust the start and end offsets of attributions based on user visible characters only. No other option is available.

Potential drawbacks:
* bigger upfront refactor
* it's a breaking change - existing users of SuperEditor who are persisting their documents today would need some kind of migration path to prevent their documents from rendering incorrectly and/or crashing due to trying bold half an emoji.
* maybe there's a case where you do want to split half of a user-visible character that we don't know of yet?

### Constructor parameter flag
We could have a flag in the constructor, for example:

```dart
SuperEditor(
  ...
  this.useOffsetsBasedOnUserVisibleCharacters = false,
);
```

(it would default to `false` so that we don't break existing users' editors)

This would probably work, but it would have some potential problems:
* it would be a bigger refactor
* it could potentially be more complex to maintain two modes of counting offsets
* maybe counting grapheme clusters all the time every time might be a performance problem, as discussed in the video chat

### A separate class for offset conversion
We could also have a separate class that users could use for converting the offsets:

```dart
class DocumentOffsetConverter {
  /// Returns a copy of this [Document], but with all start and end offsets based 
  /// on user-visible characters.
  Document withOffsetsBasedOnUserVisibleCharacters(Document document);

  /// Returns a copy of this [Document], but with all start and end offsets based 
  /// on code units instead of user-visible characters. 
  Document withOffsetsBasedOnCodeUnits(Document document);
}
```

Users could then pass a `Document` to one of those methods and get another `Document` back.

Drawbacks:
* discoverability might be lower - you need to know what you're looking for instead of just typing `document.` and getting suggestions from you IDE

I think it would be a good idea for `DocumentOffsetConverter` to coexist with the `withOffsetsBasedOnUserVisibleCharacters()` and `withOffsetsBasedOnCodeUnits()` on the `Document` class. Those methods would just directly call the `DocumentOffsetConverter`.

**Comment by bk-one** [comment] 2022-03-15 20:48
@roughike We discussed that internally, so I assume we can close this - and go with the byte-length of strings until we hit a road-block for the time being? If so, can you close it?

**Comment by osaxma** [comment] 2022-03-15 22:59
I agree that it makes sense for SuperEditor to operate in UTF-16 bytes internally when it comes to `SpanMarker`s since this is the default encoding for `String` across Dart/Flutter ecosystem. 

On the other hand, it would be very useful if the `SpanMarker`s can be converted into a more generic encoding that can be easily understood by other languages using their standard libraries. The only invariant between the different encodings are: Unicode Code Points and Grapheme Cluster. This can be seen in the following example:

```
Grapheme Cluster: '🙆‍♀️'
Unicode Code Points: [1f646, 200d, 2640, fe0f] (length: 4)  -- (String.runes in Dart)
UTF-32 Code Units: [1f646, 200d, 2640, fe0f] (length: 4) 
UTF-16 Code Units: [d83d, de46, 200d, 2640, fe0f] (length: 5) -- (String.codeUnits in Dart)
UTF-8 Code Units: [240, 159, 153, 134, 226, 128, 141, 226, 153, 128, 239, 184, 143] (length: 13)
```

The issue with the `SpanMarker` being in UTF-16 comes when working with a language that utilizes a different encoding. If the backend language is in UTF-8, then the programmer needs to convert the markers into Unicode Code Points first then convert them into UTF-16 (assuming that the language in question has support for working with UTF-16 strings).

On the other hand, if the `SpanMarker` can be converted to be based on Unicode Code Points, the markers can be directly converted to UTF-8 as I assume most language have support for code points at minimum. In fact, in Python 3.2, iterating over a string is carried based on Unicode Code Points so no conversion would be necessary in such case.

That being said, it'd be beneficial if SuperEditor makes it easy for its users to convert the `SpanMarker`s from UTF-16 to Unicode Code Points and vice versa (i.e. constructing a `SpanMarker` from Code Points) for serialization/deserialization purposes. I believe the same can be done for UTF-8 and Grapheme Clusters. 

If SuperEditor would prefer to let the user handle the conversion, then I believe the documentations for AttributedText, AttributedSpan, SpanMarker should clearly indicate that the markers are based on UTF-16 bytes where applicable.  

---- 

For reference, I came across this insightful comment about Grapheme Clusters if one decides to choose them as a base for markers:

> One other thing worth mentioning: the definition for *code point* is well-defined and very unlikely to change, but the definition for *grapheme cluster* changes from Unicode release to Unicode release.  So, different versions of Dart would have different behaviors depending on which Unicode version was bundled.
>
> _Originally posted by @sffc in https://github.com/dart-lang/language/issues/34#issuecomment-554608141_

**Comment by roughike** [comment] 2022-03-17 11:28
@bk-one yeah, it looks like we don't really need changes in the SuperEditor for the time being.

However, what @osaxma said:

> If SuperEditor would prefer to let the user handle the conversion, then I believe the documentations for AttributedText, AttributedSpan, SpanMarker should clearly indicate that the markers are based on UTF-16 bytes (String.codeUnits in dart) where applicable.

Would it make sense to at least keep this issue open, but change the scope of the issue to "update documentations on relevant Dart classes to let users know that the offsets are based on UTF-16 bytes"?

**Comment by matthew-carroll** [comment] 2022-03-17 20:08
Do you guys want extension methods for this? We can leave the natural behavior as code points and still provide the tools you need for this...

**Comment by matthew-carroll** [comment] 2022-05-12 04:29
I'm going to close this due to inactivity. If someone would like additional APIs to help with character boundaries, please file a ticket with those specific goals.

**Closed by matthew-carroll** 2022-05-12 04:29 UTC
Labels: type_bug, customer_superlist
