### ISSUE TITLE
[SuperEditor] - Hashtags and @-mentions

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1077] opened 2023-04-04 00:40 UTC
**Update: The following is a re-write of this ticket so that it describes a desired feature**

Make it possible for clients to tokenize at-mentions and hash tags.

An at-mention is a tokenization that's triggered by an @ character, e.g., @matthew-carroll

A hashtag is a tokenization that's triggered by a #, e.g., #flutter 

This feature should include the ability to anchor popovers near the token, however this ticket is only for the tokenization behavior. See #1166 for popover anchors.

## ------ Original ticket kept for posterity --------
Hi, @matthew-carroll @angelosilvestre any idea or code snippet on rendering username mentions in the editor e.g @username, thanks.

**Comment by angelosilvestre** [comment] 2023-04-04 00:47
@abidex4yemi Could you please be more specific on what you are trying to achieve?

**Comment by matthew-carroll** [comment] 2023-04-04 01:25
There won't be a dependable way to do this until we merge support for atomic commands.

Also, as @angelosilvestre implied, please ensure that tickets are filed and phrased as specific feature requests, or bug reproductions. We expect a much more detailed description than what's in this ticket. In general, tickets phrased like this one are liable to be closed as unactionable.

**Comment by abidex4yemi** [comment] 2023-04-05 00:20
@matthew-carroll @angelosilvestre  I'm sorry for creating a duplicate issue, I'm trying to achieve the same result as explained in this [ticket](https://github.com/superlistapp/super_editor/issues/736) but with slight differences such that the editor renders mentioned user in read-only mode. see screenshot below

![IMG_9784](https://user-images.githubusercontent.com/23571838/229948784-033953ee-67a0-4552-8db2-5b83d1264222.jpg)

I saw your changes in this [PR](https://github.com/superlistapp/super_editor/pull/767) and I'm thinking the same approach used for linkify of hyperlinks in the editor would solve this problem but don't quite understand how to go about it.

**Comment by angelosilvestre** [comment] 2023-04-05 16:03
@abidex4yemi So the goal for this ticket is just to apply specific formatting for the username mentions?

**Comment by abidex4yemi** [comment] 2023-04-05 23:56
@angelosilvestre Yes and also make it clickable. here's a snippet to describe the expected result `MatchText(
      pattern: r"@([a-z][a-z0-9_]{4,31})",
      renderWidget: ({required pattern, required text}) => Text(
        text,
        textDirection: TextDirection.ltr,
        style: TextStyle(
          decoration: TextDecoration.underline,
        ),
      ),
      onTap: (String username) {
        print(username.substring(1));
      },
    ),`

**Comment by angelosilvestre** [comment] 2023-04-06 00:36
@abidex4yemi This seems to be very similar to how we handle links. I think you would need the following: 

1. Define your own attribution class to represent a user mention. You can take a look at `LinkAttribution`.
2. Apply this attribution to a piece of text. For example:
```dart
 final attribution = YourUserNameAttributionClass();

 ParagraphNode(
    id: DocumentEditor.createNodeId(),
    text: AttributedText(
      text: 'This is a @username mention',
      spans: AttributedSpans(
        attributions: [
          SpanMarker(attribution: attribution, offset: 10, markerType: SpanMarkerType.start),
          SpanMarker(attribution: attribution, offset: 18, markerType: SpanMarkerType.end),
        ],
      ),
    ),
  ),
```
3. Create a method to return the text styles based on the attributtions (you will need to handle all the attributions, e.g., bold, italic) :
```dart
TextStyle myStyleBuilder(Set<Attribution> attributions) {
   // return the desired TextStyle
}
```
4. Apply the formatting using a custom stylesheet:
```dart
SuperEditor(
  // other properties.
  stylesheet: defaultStylesheet.copyWith(
    inlineTextStyler: (Set<Attribution> attributions, TextStyle existingStyle) {
      return existingStyle.merge(
        myStyleBuilder(attributions),
      );
    },
  ),
);
```

To make it clickable you'll need to create a `ContentTapDelegate` and pass it to `SuperEditor`. You can take a look at `LaunchLinkTapHandler`, which handles hovering and tapping at links.

Please let me know if this works for you.

**Comment by abidex4yemi** [comment] 2023-04-06 00:44
Thank you @angelosilvestre, will surely keep you posted.

**Comment by matthew-carroll** [comment] 2023-06-07 23:03
@miguelcmedeiros @Jethro87 @transcendr @jmatth - We're now ready to begin work on at-mentions and hashtags. Would any of you like to help fund and direct this effort?

**Comment by jmatth** [comment] 2023-06-08 20:19
@matthew-carroll We're potentially interested in this milestone depending on the scope. For our use case we'd want an autocomplete menu for @-mentions, and ideally that functionality could be expanded into a generic API for displaying menus based on entered text. If this ticket is strictly for applying attributions when text starting with an `@` is entered, then I think that can be accomplished well enough by copying + modifying the editor reaction that converts URLs to links.

**Comment by miguelcmedeiros** [comment] 2023-06-08 21:02
@matthew-carroll we are interested in this feature.
We have 2 requirements from our side:
* we need to customize the search popover;
* in some cases we want to remove the tokenized text when a selection is made, i.e. when the users uses @-mentioning to change the assignee of a task.

**Comment by matthew-carroll** [comment] 2023-06-08 21:26
@jmatth @miguelcmedeiros - It sounds like both of you are looking for popover integration, so we can add that to the requirements for the ticket.

@Jethro87 is out at the moment, but if he gets back before we finish this work then he can let us know if he needs it.

@transcendr - can you check with your team if this is something you need, and are willing to help fund for your goals?

**Comment by transcendr** [comment] 2023-06-12 11:40
@matthew-carroll I iwill certainly check and get back asap!

**Closed** 2023-08-09 22:23 UTC
Labels: area_supereditor, bounty_senior, f:superlist, time:10

**Comment by matthew-carroll** [comment] 2023-08-09 23:17
We've merged support for 3 types of tagging: stable tags, pattern tags, and action tags.

Stable tags have a composing stage and a committed stage. These are a good choice for user tagging.

Pattern tags are based on a trigger and other characters. They can be edited at any time. These are good for hash tags.

Action tags are composed, submitted, and then deleted. These tags represent a desired action, such as changing a node type, or assigning something to a user.
