### ISSUE TITLE
Space Issue

### ISSUE THREAD

**Issue by purvsonani** [superlistapp/super_editor#1462] opened 2023-09-21 11:09 UTC
While writing text, i have to click spacebar multiple times to get **space** between words, can anyone suggest if there is any solution?
Your answer will be appreciated,
Thanks.
![image](https://github.com/superlistapp/super_editor/assets/98572382/c9f5d3db-8e26-4ef3-a4e0-c3041e8128e9)

**Comment by matthew-carroll** [comment] 2023-10-14 02:48
Please include all relevant information for us to reproduce the issue:

- What version of super_editor are you using?
- What version of Flutter are you using?
- What platform are you deploying your app to?
- Are you using a software keyboard or a hardware keyboard?
- Are you running in an emulator, simulator, or physical device?
- How can we reproduce the issue that you're having?

**Comment by matthew-carroll** [comment] 2023-12-09 01:19
I'm closing this issue because it's not actionable and we haven't received any response.

**Closed by matthew-carroll** 2023-12-09 01:19 UTC
Labels: awaiting-customer-feedback
