### ISSUE TITLE
[Mobile] Auto-scroll does not work when document is placed inside a CustomScrollView

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#521] opened 2022-04-05 15:37 UTC
Steps to reproduce:
* Update "Sliver Demo Editor" so that it works on iOS:
```
inputSource: DocumentInputSource.ime,
gestureMode: DocumentGestureMode.iOS,
```
* Select a paragraph that is located at the bottom of the viewport

**Expected:** keyboard is shown and the document auto-scrolls to show the selection (caret)
**Actual:** document does not auto-scroll and selection is hidden by the keyboard

**Comment by miguelcmedeiros** [comment] 2022-04-05 15:37
Cc @matthew-carroll

**Comment by ThangVuNguyenViet** [comment] 2022-04-06 11:56
Hi @matthew-carroll . I think I can work on this. Please assign it to me

**Comment by ThangVuNguyenViet** [comment] 2022-04-08 05:50
Hi. I've made some progress but got stuck at this.

So this issue occurs when there are some slivers widgets that are above the editor in the `CustomScrollView`, which makes the original scrolling offset computation isn't correct anymore. The height of all those widgets is called X.

My approach is to get the X. By that, I got the offset from the editor to its parent `Scrollable` and pass it down to the `ensureOffsetIsVisible`

`document_gestures_touch_ios.dart`
```dart
    final editorOffset = (widget.documentKey.currentContext!.findRenderObject() as RenderBox)
        .localToGlobal(viewportBox.globalToLocal(Offset.zero));

    if (collapsedHandleOffset != null) {
      _handleAutoScrolling.ensureOffsetIsVisible(collapsedHandleOffset, editorOffset);
    } else {
      _handleAutoScrolling.ensureOffsetIsVisible(extentHandleOffset!, editorOffset);
    }
  }
```

From there I use that to compute the X, with `editorOffset.dy + currentScrollOffset == X` and add the X to the distance we need to scroll, also changed the condition originally from `_getViewportBox().size.height + currentScrollOffset` and minus X with that.

`document_gestures_touch.dart`
```dart
} else if (documentOffset.dy > _getViewportBox().size.height - editorOffset.dy) {
      editorGesturesLog.fine('The scrollable needs to scroll down to make offset visible.');
      scrollPosition.jumpTo(
        documentOffset.dy +
            _dragAutoScrollBoundary.trailing -
            _getViewportBox().size.height +
            (editorOffset.dy + currentScrollOffset),
      );
    }
```

The equation `editorOffset.dy + currentScrollOffset == X` is not true sometimes when the scrolling is taking place, and results in a bit of over-scroll, but the editor does scroll and ensures the caret is in the view. 

Except when there is a `SliverAppBar` with `FlexibleSpaceBar` and another Sliver widget both sit above the editor, then the scrolling is wrong by the height of the `flexibleSpace`. This is where I got stuck.

The changes above don't affect the default editor's scrolling.

**Comment by matthew-carroll** [comment] 2022-04-09 02:28
@ThangVuNguyenViet you mentioned where you got stuck, but what is it that has you stuck? It sounds like you found a couple places where things still don't work, like `SliverAppBar` and `FlexibleSpaceBar`, as well as issues while scrolling is happening. What kinds of things have you tried in order to resolve those issues? Where's the specific point of confusion?

**Comment by ThangVuNguyenViet** [comment] 2022-04-10 05:18
@matthew-carroll thank you for replying. I figured it out. My solution above works. I'm gonna make the PR shortly after

**Comment by ThangVuNguyenViet** [comment] 2022-04-10 07:25
@matthew-carroll I'm trying to test with goldens, but I cannot show the keyboard. I've tried tapping the document and then `focusNode.requestFocus()` but it doesn't seem to work. The red caret does appear on the image file, but since the keyboard doesn't show, no scrolling is performed.

**Comment by matthew-carroll** [comment] 2022-04-10 22:29
@ThangVuNguyenViet we aren't currently running the golden tests on CI, so I would focus on a widget test, if you can. Typically, with tests around scrolling, a widget test will carefully pump a specific number of frames, with a specific change in time, and then verify that the final scroll offset is what's expected. Can you give that a try?

**Comment by ThangVuNguyenViet** [comment] 2022-04-11 14:35
@matthew-carroll I'm still blocked at getting the keyboard to show. As far as I know, this couldn't be done with widget testing. Please tell me if you know how to show the keyboard or any way to mimic the keyboard showing behavior.

Meanwhile, I'm gonna create a PR for this without any testing. I'll add the test once we figured that out

**Comment by matthew-carroll** [comment] 2022-04-11 22:47
@ThangVuNguyenViet I'm not sure why the keyboard is relevant? When you run a widget test, there is no device at all, so there's never a keyboard.

**Comment by matthew-carroll** [comment] 2022-04-12 19:50
@ThangVuNguyenViet the question you should ask is what it means to Flutter when the keyboard is raised. You don't need the platform and the keyboard to test the Flutter UI behavior related to the keyboard.

Here are a couple guiding questions that you should look into:

- Does this situation actually depend on the keyboard, at all, or does it only depend on the available space becoming smaller?
- If the problem doesn't happen when the available space becomes smaller, then there's something about the keyboard that's relevant, but which part? What happens to a Flutter UI when the keyboard pops up? There's a concept of "view insets" and "view padding" that Flutter applies to the widget tree when the keyboard appears and disappears. If you replicate that behavior in a test, does it reproduce the bug?

Now that super_editor is beginning to stabilize in some areas, and the feature set is growing, it's important that we find ways to test behaviors like this in widget tests.

**Comment by ThangVuNguyenViet** [comment] 2022-04-14 06:51
@matthew-carroll your guidance is really helpful. It depends on the available space becoming smaller. Thanks a lot.

I minimize the space using `tester.binding.window.physicalSizeTestValue` since it changes the viewport and also calls 'didChangeMetrics`, which is the trigger for ensuring caret is visible. Please take a look at my PR of which tests have been added.

Btw, I tried changing the outer sizedbox with setState, but it doesn't trigger 'didChangeMetrics` when it runs in WidgetTest. I tried messing around with `viewInsets`, `viewPadding`, but these don't work.

**Closed** 2022-05-09 20:04 UTC
