### ISSUE TITLE
Errors after typing brackets in Chrome (Windows) with Swiss Keyboard (German)

### ISSUE THREAD

**Issue by siuvoniazzi** [superlistapp/super_editor#512] opened 2022-04-01 04:08 UTC
Test with SuperEditor 0.2.0, Flutter stable

![image](https://user-images.githubusercontent.com/9570323/161192115-8c4b1913-de3b-4367-8b7c-93be7f4cc9a1.png)

After typing brackets I can't write in SuperEditor anymore. Every key stroke then produces this error. 

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:

> Assertion failed: file:///C:/Users/siuv/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:441:16
> _pressedKeys.containsKey(event.physicalKey)
> "A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#291b2(physicalKey: PhysicalKeyboardKey#70030(usbHidUsage: \"0x00070030\", debugName: \"Bracket Right\"), logicalKey: LogicalKeyboardKey#0005d(keyId: \"0x0000005d\", keyLabel: \"]\", debugName: \"Bracket Right\"), character: null, timeStamp: 0:00:14.086800, synthesized)"

```
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/services/hardware_keyboard.dart 441:46                                                                <fn>
packages/flutter/src/services/hardware_keyboard.dart 451:14                                                                [_assertEventIsRegular]
packages/flutter/src/services/hardware_keyboard.dart 544:5                                                                 handleKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 821:57                                                                handleRawKeyMessage
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/flutter/src/services/hardware_keyboard.dart 808:51                                                                handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 77:49                                                                  <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/flutter/src/services/platform_channel.dart 76:58                                                                  <fn>
packages/flutter/src/services/binding.dart 377:35                                                                          <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/flutter/src/services/binding.dart 374:98                                                                          <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1042:13           invoke2
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/channel_buffers.dart 25:12                      invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/channel_buffers.dart 65:7                       push
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/channel_buffers.dart 130:16                     push
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 304:25            invokeOnPlatformMessage
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/keyboard.dart 130:39                       [_handleHtmlEvent]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/keyboard.dart 39:7                         <fn>
====================================================================================================

```
Backets on a Swiss Keyboard (German) are typed in a combo with Alt Graph:
![image](https://user-images.githubusercontent.com/9570323/161192831-320518e9-3690-4efb-88ed-51c90b1778c5.png)

**Comment by matthew-carroll** [comment] 2022-04-15 23:09
@siuvoniazzi can you please report this to Flutter, as mentioned in the error output that you included?

**Comment by matthew-carroll** [comment] 2023-09-03 19:56
@angelosilvestre can you check if this bug still occurs? If so, and if it's a Flutter bug, can you file a Flutter ticket or ensure that one is already filed?

**Comment by angelosilvestre** [comment] 2023-09-05 01:47
@matthew-carroll I tested in both keyboard and IME mode and it doesn't seem to happen anymore.

**Comment by matthew-carroll** [comment] 2023-09-05 04:03
Thanks. Closing at can't reproduce.

**Closed by matthew-carroll** 2023-09-05 04:03 UTC
