### ISSUE TITLE
Typing lag

### ISSUE THREAD

**Issue by Jei-sKappa** [superlistapp/super_editor#751] opened 2022-08-19 10:26 UTC
When a few hundred nodes (i noticed it with 150 nodes) are created it seems the whole view gets updated and not only the widget tree of the single node making the typing impossibile.

**Comment by jmatth** [comment] 2022-08-21 17:03
I'm seeing the same issue. To test I replaced the contents of the sample doc in the example app with the entire text of Frankenstein split into nodes by paragraph, which comes out to 812 nodes ([branch here][1]). Here's a video of what typing into that looks like in profile mode:

https://user-images.githubusercontent.com/1316184/185801628-09c353a7-22a8-4e2e-8e4e-1f6c64a675dd.mov

Interestingly, I did this exact same test when evaluating super_editor for use months ago and the performance was fine. I'll look into bisecting the git history later to see if I can pinpoint a single commit that caused the performance regression

[1]: https://github.com/jmatth/super_editor/tree/frank

**Comment by jmatth** [comment] 2022-08-23 03:32
Ok, I bisected the history and found that performance with large documents tanks at commit 57a7d72166272582cbbdedc752b6f328c0493f88. That commit rewrote most of the code for building document components. Digging deeper, it looks like the new style system caused document changes to depend heavily on [`MutableDocument.getNodeIndex`][1], and that method is very slow:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1316184/186060421-bbdd7053-3a4c-476b-a7af-cd196560dd0b.png">

I think that flamechart might be an aggregate of handling several key events but still, calls to `getNodeIndex` take up the vast majority of the time. I'd need to dig further into how all the notifiers are connected but I see a couple possibilities:

1. The presenter is marking more nodes dirty than it needs to and should be optimized to only rebuild and restyle the view models for as few nodes as possible
2. The presenter cannot be optimized further and `getNodeIndex` needs to be optimized
3. `getNodeIndex` stays slow and we add a cache for its responses somewhere in the view model / styling code

I personally like the idea of doing 2 even if 1 also happens because repeatedly walking the list of nodes with a deep equality check is probably just a bad idea for performance anyway. I hacked together a quick test with a hashmap to cache the responses from that method and the editor instantly became usable again.

@matthew-carroll: any input on the above before I start implementing a fix?

[1]: https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/core/document_editor.dart#L163-L166

**Comment by Jei-sKappa** [comment] 2022-08-23 11:00
From what I can see it seems like when a node in the UI change by typing a new character, the [_presenterListener](https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_layout.dart#L68) attacched to [presenter](https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_layout.dart#L37) in [_layout.dart](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/default_editor/layout_single_column/_layout.dart) gets fired 2 times and with that, all the quite heavy computation for checking which nodes needs to be updated is repeated. On top of that, the first notify when calls [_onPresenterMarkedDirty](https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_layout.dart#L95), following the tree of calls you get to [_notifyListenersOfChanges](https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_presenter.dart#L205) and you will see that **all** of the nodes gets marked as changed because the [first if which checks the node change](https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_presenter.dart#L228) fails.
Indeed to verify this I added a stupid hack at the and of the switch statement in the above method which controls if all the nodes are marked as changed and the performance gain is still small but relevant.
```dart
//! THIS IS A HACK
if (changedComponents.length == changeMap.entries.length) {
  return;
}
```
However, when just the caret is moving there is only 1 calls and hence proper functioning.

I also need to dig deeper into that but I think that the reason for this behavior is that when a letter is pressed the corresponding char is added to the node and the selection is moved to the right by one causing the 2 parallel calls.

**Comment by jmatth** [comment] 2022-08-23 15:13
> when a letter is pressed the corresponding char is added to the node and the selection is moved to the right by one causing the 2 parallel calls.

This is correct, and there's an issue open to fix that behavior at #748. Based on that ticket I don't think it's a trivial fix.

> ...all of the nodes gets marked as changed because the [first if which checks the node change](https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_presenter.dart#L228) fails.

Ah, I do see that. Nice catch! Debugging further, the issue seems to be [this line in `ParagraphComponentViewModel.==`][1], where it compares `textStyleBuilder` and always gets false. That field is set in [`TextComponentViewModel.applyStyles`][2], where it's assigned to a function literal. And if we read the [`Function.==` docs][3], we find:

> Different evaluations of function literals never give rise to equal function objects. Each time a function literal is evaluated, it creates a new function value that is not equal to any other function value, not even ones created by the 

So no paragraph node will ever evaluate as equal to another once one or both have been run through the style system as `textStyleBuilder` will get reassigned to a new evaluation of a function literal. Removing that comparison from the `==` method caused only the modified node to be marked as changed.

All that said, fixing `ParagraphComponentViewModel.==` still doesn't resolve the performance issues for me. This is because when the document changes, the presenter still rebuilds + styles all the component view models in [`SingleColumnLayoutPresenter._createNewViewModel`][4]. It's there, specifically as part of the style phase, that `MutableDocument.getNodeIndex` is repeatedly called and causes most of the performance hit.

So to summarize:

1. Typing causes the presenter to recalculate twice, once for the change to the content and once for the change to the selection. This already has a separate issue, #748 
2. `ParagraphComponentViewModel.==` is broken because it tries to compare separate evaluations of a function literal, which will always return false. We should either exclude `textStyleBuilder` from `==` and `hashCode` or figure out a way to make `textStyleBuilder` comparable.
3. The style phase runs for every node each time a document changes, and for each node it calls `MutableDocument.getNodeIndex`. That method walks the list of nodes to find a match each time, which gets very slow as the number of nodes increases. We should either optimize that method (and possibly other node lookup methods on `MutableDocument` while we're at it), or at least add a cache somewhere in the style phase so we don't run a deep equality check `1 + 2 + ... + n` times each time the presenter needs to update.

[1]: https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/paragraph.dart#L165
[2]: https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/text.dart#L281
[3]: https://api.dart.dev/stable/2.17.7/dart-core/Function/operator_equals.html
[4]: https://github.com/superlistapp/super_editor/blob/d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9/super_editor/lib/src/default_editor/layout_single_column/_presenter.dart#L167-L179

**Comment by jmatth** [comment] 2022-08-23 20:10
I have a branch with the `textStyleBuilder` comparison removed and a simple cache added to all `MutableDocument` queries here: https://github.com/jmatth/super_editor/tree/perf-improvements. With the entire Frankenstein document performance still isn't perfectly smooth but the editor is usable.

**Comment by matthew-carroll** [comment] 2022-08-23 21:14
I just wanted to pop in and say thanks for digging into the details. I'll review this thread when I get a chance.

**Comment by Mijawel** [comment] 2022-09-28 02:59
Thanks for the branch btw @jmatth 

Any chance this fix can be merged into the project sometime soon (or a timeline on a broader fix). Just cause this problem seems to make longer documents unusable but it's a shame to be missing out on other updates.

**Comment by jmatth** [comment] 2022-09-30 17:09
@Mijawel I've been using super_editor for several months and based on that experience I recommend just creating a fork and maintaining any changes you need there. I keep a branch with the changes I need [here][1], and rebase it onto the main branch from upstream every other week or so. As long as you rebase often enough (and possibly have [rerere][2]: turned on in git), it's not too difficult to keep your fork up-to-date.

All that being said, you can probably get away with using my optimizations without needing to fork anything. Just take my modified `MutableDocument` class, copy it into your codebase, and say it implements `MutableDocument`. Something like

```
class CachingMutableDocument with ChangeNotifier implements MutableDocument {
  // Entire contents of MutableDocument from my branch
}
```

Then just initialize a `CachingMutableDocument` instead of a `MutableDocument` and pass that to your `DocumentEditor`:

```
final editor = DocumentEditor(document: CachingMutableDocument(nodes: [...]));
```

Then everything should Just Work™️. The issue with `ParagraphComponentViewModel.==` will still cause some inefficiency, but in my testing the vast majority of the lag was caused by `MutableDocument` constantly searching through its list of nodes.

[1]: https://github.com/BringingFire/super_editor/commits/cc-custom
[2]: https://www.git-scm.com/book/en/v2/Git-Tools-Rerere

**Comment by Mijawel** [comment] 2022-10-01 13:30
Thanks. Several good suggestions! I like that your fork also seems to include the #602 PR (that bug is a bit of a pain).

**Comment by Mijawel** [comment] 2022-10-24 01:30
I recently updated my fork to the latest main commit (while retaining the caching mutable document and textStyleBuilder changes). I'm now getting lots lag on medium-to-large documents again (which doesn't appear on your branch).

Any idea what happened?

The reason I am trying to update is that when changing text formatting (e.g. selecting text, and pressing ctrl-b to bold), the formatting only appears after the text is deselected again. Is that something related to textStyleBuilder?

**Comment by matthew-carroll** [comment] 2022-10-24 01:32
@angelosilvestre can you look into this issue?

**Comment by Mijawel** [comment] 2022-10-26 00:18
Ok. It seems to be that the issue is confined to solely very large nodes on the latest commit that I checked, which is much less of problem.

**Comment by Mijawel** [comment] 2022-10-26 00:18
Ok. It seems to be that the issue is confined to solely very large nodes on the latest commit that I checked, which is much less of problem.

**Comment by Mijawel** [comment] 2022-10-26 13:41
My bad. The issue still seems to appear for me on the latest commit.

Initializing a doc like this gets me some pretty major lag.

```
for (int i=0; i<100; i++) {
      var newNode = ParagraphNode(
        id: DocumentEditor.createNodeId(),
        text: AttributedText(text: 'This is the first paragraph'),
      );
      nodeList.add(newNode);
    }
    var myDoc = MutableDocument(
      nodes: nodeList,
    );
```

**Comment by matthew-carroll** [comment] 2022-10-26 21:26
Thanks @Mijawel. Angelo is working on some improvements for this. He's found at least a couple issues that we need to solve. Let's circle back and see how the performance looks for you when Angelo has a PR up with those fixes.

**Closed** 2022-11-02 23:26 UTC
