### ISSUE TITLE
[SuperTextField][Android] - Backspace only working after numerous taps

### ISSUE THREAD

**Issue by ibrahimdevs** [superlistapp/super_editor#1112] opened 2023-05-04 09:09 UTC
I think it is related with "Predictive Text" feature on device's keyboard. Auto-correct causes some weird reactions for super text field. This video comes from one of our user, they taps multiple times backspace nothing happening on super text field. At end, it is working. There is no logs, because it is coming from our user.

https://user-images.githubusercontent.com/2773578/236160108-f8a220b5-4ee6-4082-97fe-4968d5c5b7d5.mp4

**Comment by matthew-carroll** [comment] 2023-05-05 01:08
@ibrahimdevs can you please create a minimal reproduction of the issue? I see the video, but there's no telling how many behaviors and events need to happen before this problem became evident. Please recreate this issue on your end, and then let us know what you did.

**Comment by matthew-carroll** [comment] 2023-05-05 01:14
@miguelcmedeiros a number of issues have been filed for Android text entry in `SuperTextField` - are you experiencing any issues with `SuperTextField` in Superlist on Android?

**Comment by matthew-carroll** [comment] 2023-05-05 20:18
Do you know if the problem you just now described is the same as the problem in your original post? If there are two different problems, then we should file those as two different tickets, so that we can solve both. Otherwise, we'll solve only one of them and then the ticket will be closed...

**Comment by ibrahimdevs** [comment] 2023-05-05 21:54
@matthew-carroll my second post: https://github.com/superlistapp/super_editor/issues/1112#issuecomment-1536198733 is not another problem. Only I tried to explain **what is happening** and **what may cause** the original post: https://github.com/superlistapp/super_editor/issues/1112#issue-1695594408. It was only a guess, I don't know why it is happening.

**Comment by matthew-carroll** [comment] 2023-08-29 06:17
@ibrahimdevs I'm just now getting back to this. You described some steps above, but they were a bit ambiguous. Can you provide a minimal code reproduction for an app that we can run, and then let us know what to tap on, and what to type, to cause the issue that you've run into?

**Comment by matthew-carroll** [comment] 2023-12-13 05:58
Closing this due to non-response.

**Closed by matthew-carroll** 2023-12-13 05:58 UTC
Labels: area_supertextfield, platform_android, bounty_junior, awaiting-customer-feedback
