### ISSUE TITLE
Line spacing is different when editing in the super editor vs showing the text by default

### ISSUE THREAD

**Issue by eswarm** [superlistapp/super_editor#831] opened 2022-10-15 15:03 UTC
I am running the demo_markdown_serialization.dart from the example and I have slightly edited the text. 

If for e.g we are showing the following the text. 

`Cras vitae sodales nisi. \nVivamus dignissim vel purus vel aliquet. 
`

If shows up as below, which is as expected. 

<img width="1792" alt="Screenshot 2022-10-15 at 8 27 00 PM" src="https://user-images.githubusercontent.com/381511/195993260-b913ff2f-c686-450b-8485-2d042425b42f.png">

However if I edit the text and delete the newline through the editor and press enter(new line). It shows up as below 

<img width="1786" alt="Screenshot 2022-10-15 at 8 30 20 PM" src="https://user-images.githubusercontent.com/381511/195993401-91e75272-d2ae-4a85-b43a-461c9a4ab050.png">

If i use the cursor the line space has just increased for the text. And in the markdown rendered there is an additional newline in the markdown. Both the behavior appear incorrect to me.

**Comment by matthew-carroll** [comment] 2022-10-17 21:42
@eswarm - What you're showing looks like expected behavior to me.

Can you describe what you expected to happen when you pressed `enter` and created a new paragraph?

If you want to insert a newline within an existing paragraph then you need to press a shortcut. I think it's `alt + enter` or maybe `shift + enter`. In any event, there's a key combination for that.

**Comment by eswarm** [comment] 2022-10-22 07:59
@matthew-carroll  Thought I was missing something obvious, yes I was assuming enter to create a new line instead of a paragraph. The current markdown editor is github is doing the same as is Obsidian(They are just the ones I have on my system currently).  Is there a way to override this behavior ?

**Comment by matthew-carroll** [comment] 2022-10-22 08:15
> Is there a way to override this behavior ?

You can override the default list of keyboard shortcuts for physical keyboards and take the desired action. For IME input, I'm not sure if we have an override for the action button or not, but we might. I'd take a look at the `SuperEditor` property list.

I'm going to close this issue because it sounds like `SuperEditor` is operating as intended. If you find behaviors that are hard coded and can't be configured, please open a new issue with the details.

**Closed by matthew-carroll** 2022-10-22 08:15 UTC

**Comment by eswarm** [comment] 2022-10-22 17:44
Thanks @matthew-carroll  

For anyone who is stumbling upon this the behaviour to override for keyboard would be in the constructor, override the keyboardActions with your own set of defaults. In my case I just removed shiftEnterToInsertNewlineInBlock, enterToInsertBlockNewline and created a new one which just creates a newline when you press enter key.
