### ISSUE TITLE
[SuperEditor] SliverExampleEditor does not fill available height

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#891] opened 2022-12-14 00:29 UTC
When a document is short (i.e., only one node) and I have super_editor in a `CustomScrollView`, like the SliverExampleEditor [here](https://github.com/superlistapp/super_editor/blob/main/super_editor/example/lib/demos/sliver_example_editor.dart), the editor does not take up the full height of the screen. This means that tapping anywhere on the screen will not open the keyboard (as happens with a typical super_editor implementation in a Column). 

Here's a screenshot of the SliverExampleEditor demo with a one-node document. The editor is wrapped in a yellow `ColoredBox` so the height of it can be seen:

![IMG_1111](https://user-images.githubusercontent.com/6467808/207474224-421309fe-6728-466a-b39e-5efb13df33d7.PNG)

And here's how the ExampleEditor ([here](https://github.com/superlistapp/super_editor/blob/main/super_editor/example/lib/demos/example_editor/example_editor.dart)) looks, with the same document and ColoredBox:

![IMG_1110](https://user-images.githubusercontent.com/6467808/207474210-6097846f-6174-4cb5-9a34-f6b669a07cb1.PNG)

I've tried wrapping super_editor in the SliverExampleEditor demo with various combos of `SliverFillRemaining`, `Column` (with `Expanded`), etc, but I can't seem to make the editor behave as it does in the ExampleEditor.

For reference, here's the build function of the modified SliverExampleEditor. I've removed the `SliverList` and just shortened the widget:

```
    return Scaffold(
      body: ScrollingMinimaps(
        child: Stack(
          children: [
            Positioned.fill(
              child: CustomScrollView(
                key: _scrollableKey,
                controller: _scrollController,
                slivers: [
                  SliverAppBar(
                    title: const Text(
                      'Rich Text Editor Sliver Example',
                      style: TextStyle(color: Colors.black),
                    ),
                  ),
                  SliverToBoxAdapter(
                    child: ColoredBox(
                      color: Colors.yellow,
                      child: SuperEditor(
                        editor: _docEditor,
                        stylesheet: defaultStylesheet.copyWith(
                          documentPadding: const EdgeInsets.symmetric(vertical: 56, horizontal: 24),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            if (_showDebugPaint) _buildScrollingMinimap(),
          ],
        ),
      ),
    );

```

**Comment by Jethro87** [comment] 2022-12-14 00:48
It's possible to do something like adding a `SliverFillRemaining` widget below `SuperEditor` in the `CustomScrollView` that contains a `GestureDetector`, which onTap creates a selection in the document, but I'm wondering if this is the recommended solution.

**Comment by raulmabe-labhouse** [comment] 2023-01-18 10:55
> It's possible to do something like adding a SliverFillRemaining widget below SuperEditor in the CustomScrollView that contains a GestureDetector, which onTap creates a selection in the document, but I'm wondering if this is the recommended solution.

The overall scroll extent of the `CustomScrollView` is bigger with this workaround, which is not ideal... 😢

**Comment by miguelcmedeiros** [comment] 2023-03-31 12:13
@Jethro87 @raulmabe-labhouse 
It seems like you solved this situation. 
Would you mind sharing a code sample of how you solved it?

I need to do the same, but simply using `SliverFillRemaining` with `hasScrollBody: false` did not work.

**Comment by Jethro87** [comment] 2023-03-31 16:09
@miguelcmedeiros Here's how I solved it:

```
return Stack(
  children: [
    Positioned.fill(
      child: CustomScrollView(
        key: _scrollableKey,
        controller: _scrollController,
        slivers: [
          SliverToBoxAdapter(
            child: _buildEditor(
              context,
            ),
          ),
          SliverFillRemaining(
            hasScrollBody: false,
            child: Semantics(
              label: 'Tap to edit entry',
              button: true,
              child: GestureDetector(
                onTap: _setSelectionAtEndOfDocument,
              ),
            ),
          ),
        ],
      ),
    ),
...
```

The functions to set selection:
```
  void _setSelectionAtEndOfDocument() {
    if (_composer.selection != null) {
      return;
    }

    final DocumentPosition? position = _editContext.documentLayout.findLastSelectablePosition();

    if (position == null) {
      return;
    }

    final newSelection = DocumentSelection.collapsed(
      position: position,
    );

    _setSelection(newSelection);
  }

  void _setSelection(DocumentSelection? selection) {
    if (selection != null) {
      _composer.selectionNotifier.value = selection;
      _editorFocusNode.requestFocus();
    }
  }
```

**Comment by miguelcmedeiros** [comment] 2023-03-31 22:39
@Jethro87, thanks for the snippets 🙌 

From the previous comments I thought the solution was without the extra sliver with the gesture detector inside.
@matthew-carroll, do you think that this is something that can be done within `SuperEditor`, so that client code does not need to add this extra sliver to detect taps on the empty space below the editor, so that the editor gains focus?
It works really well when the document is not placed in a `CustomScrollView`.

**Comment by matthew-carroll** [comment] 2023-04-03 21:56
@miguelcmedeiros we can probably figure something out.

Can you and @Jethro87 describe the expected behavior? This ticket discusses an expectation when there's only a `SuperEditor` in a `CustomScrollView`. What about when there's content above? Or below it? When exactly should `SuperEditor` size itself in a way that's different from its intrinsic height?

Also, @miguelcmedeiros and @Jethro87 - can each of you let me know if you'd like to split funding on this? @Jethro87 I wasn't sure if you were satisfied with your workaround, or if you'd like a more canonical solution.

**Comment by Jethro87** [comment] 2023-04-04 03:19
@matthew-carroll I'm satisfied with my workaround.

**Comment by miguelcmedeiros** [comment] 2023-04-04 08:14
@matthew-carroll in Superlist we have 3 different cases:
1. `SuperEditor` is placed in the last sliver
2. `SuperEditor` is not placed in the last sliver and it should have a minimum height
3. `SuperEditor` is not placed in the last sliver and it should take as much space as possible

**Comment by matthew-carroll** [comment] 2023-08-29 06:51
@angelosilvestre based on @miguelcmedeiros's last comment, why don't you see what we might do about this sliver sizing issue. See if you can find an approach that doesn't require us to add any kind of public property to `SuperEditor`.

**Comment by angelosilvestre** [comment] 2023-09-14 23:21
@matthew-carroll I tested and it seems to be working without changed in the editor. I tested the sliver demo with the following modified build method:

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ScrollingMinimaps(
        child: Stack(
          children: [
            Positioned.fill(
              child: CustomScrollView(
                key: _scrollableKey,
                controller: _scrollController,
                slivers: [
                  SliverAppBar(
                    title: const Text(
                      'Rich Text Editor Sliver Example',
                      style: TextStyle(color: Colors.black),
                    ),
                  ),
                  SliverFillRemaining(
                    child: ColoredBox(
                      color: Colors.yellow,
                      child: SuperEditor(
                        document: _doc,
                        editor: _docEditor,
                        composer: _composer,
                        stylesheet: defaultStylesheet.copyWith(
                          documentPadding: const EdgeInsets.symmetric(vertical: 56, horizontal: 24),
                        ),
                      ),
                    ),
                 ),                
                ],
              ),
            ),
            if (_showDebugPaint) _buildScrollingMinimap(),
          ],
        ),
      ),
    );
  }
```

1. Last sliver:

https://github.com/superlistapp/super_editor/assets/7597082/6498be22-2505-454b-a04b-3f782f59d8f9

2. Not last sliver and taking minimum height:

https://github.com/superlistapp/super_editor/assets/7597082/0e38cbb4-6233-492c-b57f-b33fb273f3bb

3. Not last sliver and taking maximum heigh:


https://github.com/superlistapp/super_editor/assets/7597082/3bd32791-15c3-4e9f-bdfc-bf3ff71fa9c2

For this case, is that what is needed? Or should it display the text below the editor and the editor should take the remaining space?

**Comment by matthew-carroll** [comment] 2023-09-15 17:53
@miguelcmedeiros can you take a look at @angelosilvestre's video examples up above?

**Comment by miguelcmedeiros** [comment] 2023-09-15 18:25
@matthew-carroll it looks good. From my side, we can close this issue.

**Closed** 2023-09-15 18:38 UTC
Labels: area_supereditor, bounty_junior, f:superlist, time: 5
