### ISSUE TITLE
[SuperEditor] [Web] Cannot delete a selection after dragging to select

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1447] opened 2023-09-14 00:07 UTC
Repro: Run the example app targeting web and try to delete text after dragging the mouse to select. Sometimes it will work, but it often throws the following error:

```
(47.837) editor.keys > INFO: Handling key press: RawKeyDownEvent#ee45c(logicalKey: LogicalKeyboardKey#d5887(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), physicalKey: PhysicalKeyboardKey#7002a(usbHidUsage: "0x0007002a", debugName: "Backspace"), repeat: false)
Error: Assertion failed: org-dartlang-sdk:///lib/ui/text.dart:547:16
start >= -1
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/ui/text.dart 547:26                                                           new
lib/_engine/engine/text_editing/text_editing.dart 573:48                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```
The final selected text threw the error.

https://github.com/superlistapp/super_editor/assets/6467808/9765104a-377f-4823-9c82-6597d75ef7a2

I'm running Flutter 3.13.3 stable and super_editor stable.

cc @matthew-carroll

**Comment by Jethro87** [comment] 2023-09-14 00:17
It also throws if you try to enter a character after selecting a bunch of text.

```
(39.574) editor.keys > INFO: Handling key press: RawKeyDownEvent#24381(logicalKey: LogicalKeyboardKey#00074(keyId: "0x00000074", keyLabel: "T", debugName: "Key T"), physicalKey: PhysicalKeyboardKey#70009(usbHidUsage: "0x00070009", debugName: "Key F"), repeat: false)
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

https://github.com/superlistapp/super_editor/assets/6467808/fe710c03-cb54-4cae-b027-5b9c038f03bf

**Comment by Jethro87** [comment] 2023-09-14 00:37
@angelosilvestre On flutter master / super_editor main I have not been able to reproduce this issue.

**Comment by matthew-carroll** [comment] 2023-09-15 17:45
@Jethro87 you mentioned this issue as a new one that you'd like us to fix, but it sounds like it's already fixed? Was there anything more you wanted to see us do on this one? Based on the comments above it looks like we're waiting for Flutter to roll `master` to `stable`?

**Comment by Jethro87** [comment] 2023-09-15 18:06
@matthew-carroll My goal is to run web right now without having to be on Flutter master / super editor main. Was there an interim fix in super editor that handled upstream selections during the time before the Flutter fix landed? If so, would it be possible to bring that back to super editor stable until the fix gets to Flutter stable?

**Comment by matthew-carroll** [comment] 2023-09-15 18:22
@angelosilvestre what is the root cause of this issue on `stable`? Did we do something to add to this problem? Or has this problem always been here due to the Flutter engine's incorrect handling of text selection direction on web?

**Comment by angelosilvestre** [comment] 2023-09-15 21:22
@matthew-carroll The root cause is an issue with Flutter web related to upstream selections. It seems there were some assumptions that selections are always normalized. 

I'm afraid that there is nothing we can do until the fix for it lands on Flutter stable.

**Comment by matthew-carroll** [comment] 2023-09-16 04:02
@angelosilvestre can you remind me if this was working previously due to a previous, greater intervention by Super Editor and now it's not working because we moved more responsibility to the IME? Or do you think this was always broken?

**Comment by angelosilvestre** [comment] 2023-09-17 22:37
@matthew-carroll I tested with a revision before #1269 and these errors also happened. This suggests that it was always broken.

**Comment by matthew-carroll** [comment] 2023-09-20 22:47
@Jethro87 it looks like this error has always been here, as a result of a Flutter engine bug. Flutter has fixed that on `master` but it still needs to work its way to `stable`. Do you have any other input on this issue? Or any reason to think that there might be something we should do in the meantime to unblock you?

**Comment by Jethro87** [comment] 2023-09-22 15:17
@matthew-carroll Thanks for digging in. I'm a bit surprised, as I would have thought I had tested this functionality, but it's possible I didn't. I don't have input right now - we've resolved to run the beta version of our web app in Flutter master and super_editor main. It's not ideal, but I don't see another way forward right now.

**Comment by matthew-carroll** [comment] 2023-09-22 18:55
Yeah, not ideal, but that seems to be the state of Flutter at the moment. I'm going to close this issue. Please re-open if the problem comes back on `master`.

**Closed by matthew-carroll** 2023-09-22 18:55 UTC
