### ISSUE TITLE
StateError caused by `SuperSelectableTextState.getCharacterBox` as it tries to access the first item of an empty list

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#378] opened 2022-01-01 17:41 UTC
### Issue:
I'm getting the following error when performing text selection:

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following StateError was thrown during a scheduler callback:
Bad state: No element

When the exception was thrown, this was the stack
#0      List.first (dart:core-patch/growable_array.dart:339:5)
#1      SuperSelectableTextState.getCharacterBox
#2      SuperSelectableTextState.getLineHeightAtPosition
#3      _TextComponentState.getRectForPosition
#4      _DefaultDocumentLayoutState.getRectForPosition
#5      _DocumentMouseInteractorState._ensureSelectionExtentIsVisible
#6      _DocumentMouseInteractorState._onSelectionChange.<anonymous closure>
#7      SchedulerBinding._invokeFrameCallback
#8      SchedulerBinding.handleDrawFrame
#9      SchedulerBinding._handleDrawFrame
#13     _invoke (dart:ui/hooks.dart:150:10)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#15     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
```

The stack trace points to the following code where `_renderParagraph !.getBoxesForSelection` is apparently returning an empty list:
https://github.com/superlistapp/super_editor/blob/148224e5381251101def23ed7f7b00a4d51c2077/super_editor/lib/src/infrastructure/super_selectable_text.dart#L287-L293

### Reproduction Steps:
- Launch SuperEditor
- Delete Everything in the default example
- Paste the following Arabic Text:
```
لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.
و سأعرض مثال حي لهذا، من منا لم يتحمل جهد بدني شاق إلا من أجل الحصول على ميزة أو فائدة؟ ولكن من لديه الحق أن ينتقد شخص ما أراد أن يشعر بالسعادة التي لا تشوبها عواقب أليمة أو آخر أراد أن يتجنب الألم الذي ربما تنجم عنه بعض المتعة ؟ 
علي الجانب الآخر نشجب ونستنكر هؤلاء الرجال المفتونون بنشوة اللحظة الهائمون في رغباتهم فلا يدركون ما يعقبها من الألم والأسي المحتم، واللوم كذلك يشمل هؤلاء الذين أخفقوا في واجباتهم نتيجة لضعف إرادتهم فيتساوي مع هؤلاء الذين يتجنبون وينأون عن تحمل الكدح والألم .
```
- Try dragging the selection from bottom to top and vice versa as shown in this video (doesn't always occur in the first time):

https://user-images.githubusercontent.com/46427323/147856940-f3f2615e-880a-4023-a434-ebc0c6de2f2e.mov

This was produced on a macOS using:
```
Flutter: Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en
SuperEditor: latest main as of the issue date. 
```

**Comment by osaxma** [comment] 2022-01-02 20:35
I initially thought the issue was related to Arabic characters but it looks like any non-latin characters or a string with emojis like this one will also reproduce:

```
Text 😀 with 😃 random 😄 emojis 😁 to 😆 show 😅 that 😂 selection 🤣 will 🥲 throw ☺️ an 😊 exception🤯
```

--- 

It looks like the issue is coming from Flutter's RenderParagraph if I'm not mistaken. To demonstrate, the following are screenshots from both SuperEditor and Flutter: 

- SuperEditor
<p align=center><img width="583" alt="Screen Shot 2022-01-02 at 11 11 00 PM" src="https://user-images.githubusercontent.com/46427323/147888211-103977a9-1b14-4649-bbd3-1d8c9bc16cdd.png"></p>

<p align=center><img width="581" alt="Screen Shot 2022-01-02 at 11 11 18 PM" src="https://user-images.githubusercontent.com/46427323/147888217-4ea55265-b9cc-48b8-b709-edc49f9c4723.png"></p>

- Flutter
<p align=center><img width="805" alt="Screen Shot 2022-01-02 at 11 30 06 PM" src="https://user-images.githubusercontent.com/46427323/147888699-a3b4feff-3163-4f0e-8300-f8285a7c748d.png"></p>

<p align=center><img width="738" alt="Screen Shot 2022-01-02 at 11 28 26 PM" src="https://user-images.githubusercontent.com/46427323/147888701-ac39a504-77cd-4e75-a806-aba3721132f3.png"></p>

Zooming in screenshots above shows overlapping boxes and also empty spaces between characters. I assume `RenderPargraph .getBoxesForSelection` is returning an empty list for that reason. 

Possible related issue on Flutter:
- https://github.com/flutter/flutter/issues/68675
- https://github.com/flutter/flutter/issues/39755

**Comment by matthew-carroll** [comment] 2022-07-04 01:54
FYI @angelosilvestre - This problem may already be solved, but take a look and see if you can reproduce it.

**Comment by angelosilvestre** [comment] 2022-07-12 23:44
I tried both examples and it seems the issue is already solved. Also, since https://github.com/superlistapp/super_editor/pull/616 `getCharacterBox` checks if `getBoxesForSelection` returns an empty list. I'm going to close this ticket.

**Closed by angelosilvestre** 2022-07-12 23:44 UTC
Labels: bounty_junior
