### ISSUE TITLE
[IOS] The enter key of the soft keyboard is not triggered properly

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1157] opened 2023-06-05 10:01 UTC
In the example program, moving the cursor to the end of the TaskNode and pressing the enter key will not create a new TaskNode, nor will it execute the `enterToInsertNewTask` logic in the `defaultImeKeyboardActions` list.

The 'newline' logic was executed in the "DeltaTextInputClientDecorator" class.

On the Android side, it is exactly the opposite.

<img width="367" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/5c9a679e-dd51-4075-ac4e-05eec7277cba">

<img width="1019" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/567b0b5c-ae25-4234-b179-a753e2d31e26">

<img width="820" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/9d3814ef-a011-47b2-ba27-b272d8ec205b">

<img width="641" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/7fb0199e-8e94-4d3b-9d0d-374670f266b4">

**Comment by Dboy233** [comment] 2023-06-06 00:39
> @Dboy233 Could you please try changing this line:
> 
> https://github.com/superlistapp/super_editor/blob/dbda8f465c22932057c2fc291a9070d46d20482d/super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart#L106
> 
> to:
> 
> ```dart
> if (defaultTargetPlatform == TargetPlatform.android || defaultTargetPlatform == TargetPlatform.iOS || kIsWeb) {
> ```

Yes, I tried. It doesn't seem to work. Although the line break character was forwarded, there was no proper line break and no new 'TaskNode' was added.
<img width="1046" alt="Snipaste_2023-06-06_08-31-35" src="https://github.com/superlistapp/super_editor/assets/37604230/780e1d08-7a6b-47ba-80ac-fd5c2f8c320d">

Finally came to this position

<img width="1347" alt="Snipaste_2023-06-06_08-34-46" src="https://github.com/superlistapp/super_editor/assets/37604230/27013a25-8121-41bb-9572-95fa0238f99a">

**Comment by Dboy233** [comment] 2023-06-06 00:50
#### The logical of this part of the code was not executed.
<img width="1129" alt="Snipaste_2023-06-06_08-48-48" src="https://github.com/superlistapp/super_editor/assets/37604230/e936fab0-7fb1-4c59-ae46-f39ffae34ea0">

**Comment by Dboy233** [comment] 2023-06-06 02:17
> @Dboy233 We probably need to change `_insertNewlineInDeltas` to handle the case where the selected node is a task node and execute an `InsertNewTaskOrSplitExistingTaskCommand`

Yes, it does need modification. However, what if I have custom components and a custom line break strategy? How should they be handled?

**Comment by Dboy233** [comment] 2023-06-06 07:10
Please watch this video. When I use the on-screen keyboard on the iOS simulator, it doesn't work. However, when I use a physical keyboard, it works normally and the `Focus.onKey` method responds to key presses on the physical keyboard.

https://github.com/superlistapp/super_editor/assets/37604230/5a382194-9dc8-454e-b3b0-d8122d79382d

**Comment by Dboy233** [comment] 2023-06-06 08:03
That's frustrating. I found this issue on "https://github.com/flutter/flutter/issues/108210".

**Comment by angelosilvestre** [comment] 2023-06-06 09:53
> Also, why wasn't the 'Focus.onKey' method executed on the iOS platform? I don't quite understand why.

On mobile we don't receive key presses. Instead we receive deltas which represent a change in the text. In this case we receive an insertion of `\n`

**Comment by Dboy233** [comment] 2023-06-07 05:38
Currently, I have added a temporary line break strategy by overriding the `void performAction(TextInputAction action)` method of `DeltaTextInputClientDecorator`. Although this is not the optimal solution, based on the execution results of the program, it achieves my expected effect.

<img width="637" alt="Snipaste_2023-06-07_13-30-00" src="https://github.com/superlistapp/super_editor/assets/37604230/785c20b0-7bad-49ea-9984-a316e7bc5089">

**Comment by matthew-carroll** [comment] 2023-06-09 18:39
@angelosilvestre there's a lot of stuff in this thread so I haven't looked closely. Does this seem like a legitimate bug? Should I assign it to you?

@Dboy233 I see that you're filing a lot of tickets. We appreciate the help with finding bugs. I wanted to let you know that you'll have more success getting fixes from us if you file tickets more concisely. In general, you should write the shortest ticket possible, while including the necessary information to understand the bug. The more you write, and the more you post, the less likely that we are to take the time to read through all of it. We just need to know the problem.

**Comment by angelosilvestre** [comment] 2023-06-09 21:06
@matthew-carroll It seems like a legitimate bug. I haven't tested yet after the atomic was merged to see if the issue is still present. Will test it when I get a moment.

**Comment by angelosilvestre** [comment] 2023-06-13 23:08
@matthew-carroll Sorry for the delay. I tested it in the current main and the issue still exists. You can assign it to me.

**Closed** 2023-07-20 20:39 UTC
Labels: area_supereditor, bounty_junior, f:superlist, time: 5
